### ISSUE TITLE
MSRM Delete Instance/Backup online instance

### ISSUE THREAD

**Issue by ychakka** [WaelHamze/dyn365-ce-vsts-tasks#10]
Hello,

Have couple of questions regarding the tasks which are part of your MSCRM data tools.

1. MSCRM Delete Instance (Will this really delete my whole CRM instance? or i misread it. Please help me what it actually does?)

2. MSCRM Online provision instnace. (what does it do?)

3. MSCRM update secure configuration

4. MSCRM backup online instance (Will this really backup the whole CRM online instance?)

Please help me figure out if any of the tasks in your add-on will delete/refresh my whole CRM instance data as i am bit worried about it.

Thanks in advance

**Comment by WaelHamze** [comment]
@ychakka 

1. Yes will delete the instance
2. Creates a new CRM instance
3. Updates the secure configuration of plug-in steps
4. Yes

MS doesn't provide reset and copy APIs yet. You using the above you could delete and create the instance and then apply any solutions/data on top of that.
