### ISSUE TITLE
Extract Solution - Error When No Mapping File and Manually Triggered Release

### ISSUE THREAD

**Issue by andypleasants** [WaelHamze/dyn365-ce-vsts-tasks#100]
### Scenario
I have a manually triggered release and after exporting a solution I want to extract the solution (using the relevant tasks), **I do not want to specify a mapping file**.  

### Error
I get an error saying that access to the path `D:\a\r1\a` is denied.  

### Reason(?)
It seems that the defaults for $mappingFile and $env:BUILD_SOURCESDIRECTORY are as follows:

`
2019-07-29T12:39:01.7729772Z ##[debug]mappingFile = D:\a\r1\a
....
2019-07-29T12:39:01.7832481Z ##[debug]sourcesDirectory = 
2019-07-29T12:39:01.7851950Z ##[debug]binariesDirectory = 
`

However the check on whether to make mapping file null is as follows:

`
if ($mappingFile -eq $sourcesDirectory)
{
	$mappingFile = $null
}
`

Which is not the case; so $mappingFile is not set to null.  

### Suggested Solution
Add an OR statement to the if statement to check whether $env:BUILD_SOURCESDIRECTORY is null in addition to the existing check

**Comment by andypleasants** [comment]
Incidentally I am happy to work on this if need be :)

**Comment by WaelHamze** [comment]
@andypleasants thanks for the feedback, I would be interested to know why you need to unpack in release instead of build but we can certainly make this task more flexible

**Comment by andypleasants** [comment]
I would like to extract the customisations.xml file in a DevOps pipeline in an attempt to create a “release notes” style file from the XML

Thanks
Andy

**Comment by WaelHamze** [comment]
@andypleasants does the above commit fix your issue?

Are you able to share a bit more on how you use the xml to generate release notes?

**Comment by andypleasants** [comment]
Sure I’ll check out the commit; what’s the best way to get the committed version into DevOps?

I’m just running an XSLT transformation against the customisations.xml file to produce a simple HTML doc.

Thanks
Andy

**Comment by WaelHamze** [comment]
Fixed in last release
