### ISSUE TITLE
Select-WhoAmI can't be used in loop

### ISSUE THREAD

**Issue by nobspulsar** [WaelHamze/dyn365-ce-vsts-tasks#102]
Hi Team,

I have been trying to use Select-WhoAmI function to check the status of a couple of dynamics CRM instances in for each loop.

But noticed that if we run the command consecutively for two connections (instances), then the second run will pick the connection of the first instance only.  It seems  PS caches the connection string and releases it only after 15 mins or so. Tried clear-variable and other PS options but no luck.  

Could you please suggest any option to clear the XRM sessions so that I could use WhoAmI function in a loop?

Below is a snippet shows the org id is same for both the run even for different instances. 
Note: Some of the values are masked

---------
PS C:\windows\system32> Select-WhoAmI -ConnectionString 'AuthType=Office365;Url=https://itopsgold.crmx.dynamics.com/;Username=$username;Password=$pass;'
UserId         : xxxxxxxx-xxxx-xxxx-9ca4-8e852a8281db
BusinessUnitId : xxxxxxxx-xxxx-xxxx-a9de-000d3ad1c8a7
OrganizationId : xxxxxxxx-xxxx-xxxx-b4b0-534b691c218e
ResponseName   : WhoAmI
Results        : {[UserId, xxxxxxxx-xxxx-xxxx-9ca4-8e852a8281db], [BusinessUnitId, xxxxxxxx-xxxx-xxxx-a9de-000d3ad1c8a7], [OrganizationId, xxxxxxxx-xxxx-xxxx-b4b0-534b691c218e]}
ExtensionData  : System.Runtime.Serialization.ExtensionDataObject

---------------
PS C:\windows\system32> Select-WhoAmI -ConnectionString 'AuthType=Office365;Url=https://itopsauto.crmx.dynamics.com/;Username=$username;Password=$pass;'
UserId         : xxxxxxxx-xxxx-xxxx-9ca4-8e852a8281db
BusinessUnitId : xxxxxxxx-xxxx-xxxx-a9de-000d3ad1c8a7
OrganizationId : xxxxxxxx-xxxx-xxxx-b4b0-534b691c218e
ResponseName   : WhoAmI
Results        : {[UserId, xxxxxxxx-xxxx-xxxx-9ca4-8e852a8281db], [BusinessUnitId, xxxxxxxx-xxxx-xxxx-a9de-000d3ad1c8a7], [OrganizationId, xxxxxxxx-xxxx-xxxx-b4b0-534b691c218e]}
ExtensionData  : System.Runtime.Serialization.ExtensionDataObject

**Comment by WaelHamze** [comment]
https://docs.microsoft.com/en-us/dynamics365/customer-engagement/developer/xrm-tooling/use-connection-strings-xrm-tooling-connect#connection-string-parameters

You need to add RequireNewInstance=true
