### ISSUE TITLE
ADO Online + CDS

### ISSUE THREAD

**Issue by Triangle333** [WaelHamze/dyn365-ce-vsts-tasks#105]
1. Will this tool work with Azure DevOps in the cloud?
2. Can this article be used to install it there https://docs.microsoft.com/en-us/azure/devops/marketplace/install-extension?view=azure-devops?
3. Will it work with CDS instances?
4. Xrm.Framework.CI.PowerShell.Cmdlets.dll sources are closed? Is this open-source or not?

**Comment by RonnyVDS** [comment]
1. Yes
2. Yes
3. Yes
4. See https://github.com/WaelHamze/xrm-ci-framework

**Comment by Triangle333** [comment]
Thank you for the prompt response!
