### ISSUE TITLE
Config file parsing error

### ISSUE THREAD

**Issue by ychakka** [WaelHamze/dyn365-ce-vsts-tasks#11]
Hello,

I got the error "Config file parsing error"while executing the task MSCRM package deployer as part of my release pipeline. How should i debug it? Or please suggest me any solution where i am going wrong.

Thanks

**Comment by stephenacrown** [comment]
Hi,

Strangley, we've just been working through this problem as well, so thought I'd share our solution. ;-)

In essence, the Solution file (.zip) is not copied at build time to the correct directory (possibly something we've missed as we're new to all of this (Azure DevOps and Dynamics 365!)

The error we were receiveing below:

![image](https://user-images.githubusercontent.com/38353501/47421589-d5558880-d778-11e8-840a-cf0a751297d6.png)

We've worked around this by copying in the missing Solution .zip file from the source directory in the build phase of the pipeline:

![image](https://user-images.githubusercontent.com/38353501/47420943-79d6cb00-d777-11e8-80ad-1e3fbca2b3c7.png)

The below extension was very useful for showing what files were in place (and therefore we deduced a file was missing based on manual GUI execution of the same tool):
![image](https://user-images.githubusercontent.com/38353501/47421294-30d34680-d778-11e8-8c36-31bf80d871a6.png)

Ideally, the PackageDeploy.log should be created and the following basic task should be able to upload the log file specified to the Build agent logs download (but no log file exisits...even though from reading the code, the lof file should exist in the $PackageDirectory folder)

![image](https://user-images.githubusercontent.com/38353501/47421392-6841f300-d778-11e8-852d-ce965e544069.png)

@WaelHamze - These are great extensions firstly. Thank you for your time creating them. 
Are you able to comment on the location of the PackageDeploy.log file as per the following documention? We cannot find nor can we seem to crearte a detailed log file for the deployment to help troubleshooting, so would be useful if you were able to advide further on this?
https://docs.microsoft.com/en-us/dynamics365/customer-engagement/admin/deploy-packages-using-package-deployer-windows-powershell#troubleshoot-package-deployment-issues-by-using-log-files

Hopefully this helps you and anyone else that comes across this error.

**Comment by WaelHamze** [comment]
@stephenacrown Thank you for your feedback and collaboration

LogWriteDirectory parameter is set to the package folder. Then I attempt to upload it to the pipeline logs in this script: https://github.com/WaelHamze/dyn365-ce-vsts-tasks/blob/master/BuildTools/Xrm.CI.Framework.BuildTools/Tasks/MSCRMPackageDeployer/MSCRMPackageDeployer.ps1

Something may have changed, so I will need to verify if this still works with latest version.

Is this what you are after?

**Comment by stephenacrown** [comment]
Hi,

Yes, the file you referenced is uploaded, but didn’t seem (or appear to be anyway) as verbose or provide the detail (at the time) that the PackageDeploy.log contained when we tested running via the PackageDeployer.exe GUI interface. 

Apologies, this then is a misunderstanding as it appears the powershell method your extension uses outputs a differently named log file to that I referenced in the documentation from Microsoft.

**Comment by WaelHamze** [comment]
I think you can get the most information out of this if you set system.debug to true in the pipeline. The log file seems contains much less information than you can see in the console which is a shame.
