### ISSUE TITLE
Error in Import Config Migration Data Tasks

### ISSUE THREAD

**Issue by LycraLout** [WaelHamze/dyn365-ce-vsts-tasks#110]
I have a Config Migration Tool data package that can be deployed via the desktop tool just fine. When attempting to deploy via the Azure DevOps task, it reports as successful, but no data goes in. Turning on system.debug, I get the following:

```
2019-09-12T17:33:08.5614193Z ##[debug]Beginning Import To CRM.. Importing 6 entities - 291 records--Working
2019-09-12T17:33:08.5760376Z ##[debug]Running Schema Validation--Working
2019-09-12T17:33:10.9237383Z ##[debug]Schema Validation Complete--Complete
2019-09-12T17:33:10.9352859Z ##[debug]Unable to parse timestamp '29/08/2019 17:48:29' in data. Invalid format.--Failed
2019-09-12T17:33:11.0649985Z ##[debug]Leaving ImportCMData.ps1
2019-09-12T17:33:11.0669464Z ##[debug]Leaving MSCRMImportCMData.ps1
2019-09-12T17:33:11.1083275Z ##[section]Finishing: MSCRM Import Standard Data
```

That date is the timestamp at the very top of the data.xml. I'm in the UK where that is a valid date. I get this failure with all data packages in DevOps but they do Import fine when using the desktop tool.

Firstly, could the tooling be modified to parse the date locale agnostic.
Secondly, could the Task report back a failure when a failure to import does occur.

Thanks

**Comment by LycraLout** [comment]
Further to the above, I manually edited the data.xml timestamp to 10/08/2019 (ie, friendly for the American format), and the Task went through successfully.

**Comment by WaelHamze** [comment]
@LycraLout This task is calling the MS API I have not much control over what it is doing internally. What the export and import running under a user with the same timezone settings?

You could consider writing a powershell script to adjust the datetime format of the file before import.

**Comment by LycraLout** [comment]
I suspected something like that might be the case. The export occurs locally on my desktop with UK Regional Settings. The Import will be running on the Regional Settings of the Build Agent in Azure DevOps. I'll see if we can fiddle with that. Anyone have any pointers?

Otherwise we'll fiddle with the dates post export or pre import somehow.

**Comment by WaelHamze** [comment]
@LycraLout I presume this is working for you now?

**Comment by LycraLout** [comment]
> @LycraLout I presume this is working for you now?

It's the same behaviour. We workaround via manipulating the date in source. We don't commit the source zip any more. The source zip is extracted and the xml files committed. In our Release pipeline we create the zip from the source and use that as the source for the Import task. So it has actually improved our process by having the data.xml in source rather than a zip.

I'm happy for this to be closed. I appreciate it's a problem with the API rather than the Task.

**Comment by WaelHamze** [comment]
@LycraLout thanks for the update. What you describe seems to make sense. Glad you found a workaround for this issue. I will close this issue now.
