### ISSUE TITLE
Workflows not activated after solution import, with 'Publish Workflows' ticked

### ISSUE THREAD

**Issue by bwmodular** [WaelHamze/dyn365-ce-vsts-tasks#115]
When we import a solution containing worflows using the MSCRM Import Solution task, with the 'Publish Workflows' option ticked, our workflows are set to Draft after the task is finished. Even if the workflow was previously Activated, it is set back to Draft after the import. The workflows can be Activated manually after deployment so there's nothing stopping the workflows from being activated.

We think this is something that's started to happen very recently - any one else noticed this - could it be an October Release issue?

We notice that the task finishes with a status of 'Warning' and in the logs it says: 
##[warning]Total number of unprocessed components: 18 (where 18 is the number of workflows which should be activated)
In the solution import log (spreadsheet) we can see that the Workflow Import has been succesful, but the Workflow Activation is marked as 'Unprocessed'.

**Comment by drivardxrm** [comment]
I don't know if it is related, but we opened a case at MSFT last week for solution import that failed at workflow activation. They have identified the problem and it was related to the October Release. They have applied a fix (at least in Canadian datacenter). We don't see the issue anymore.

**Comment by bwmodular** [comment]
Thanks for the update @drivardxrm  Sorry for delay -  I was on leave last week. I also have a case open with MS about this - is there any way you could share any more details? An incident number might help them establish whether this is the same issue, for example.

**Comment by WaelHamze** [comment]
@bwmodular @drivardxrm I haven't noticed this, are you still having issues?

**Comment by drivardxrm** [comment]
@WaelHamze since it was a known product issue it was resolved quite quickly by the product team. We dont see the failures anymore.

**Comment by WaelHamze** [comment]
@drivardxrm thx for confirmation I will close this case now.

**Comment by bwmodular** [comment]
@drivardxrm @WaelHamze Can confirm this has been fixed - product issue, not a problem with the VSTS task.
