### ISSUE TITLE
Cannot edit the description of patch solution

### ISSUE THREAD

**Issue by aboodh95** [WaelHamze/dyn365-ce-vsts-tasks#117]
Hi,

I'm trying to creaet a patch solution then i'm updating the Patch discrotion, i used "MSCRM Get Latest Patch" to get the patch name, then i'm passing it to "MSCRM Update Solution Description", but i'm getting an error
`##[error]Solution patch with version 3.6.1.0 already exists. Updating patch is not supported.`
this is the debug log
`
##[debug]Modified Security Protocol: Ssl3, Tls, Tls11, Tls12
##[debug]Connecting to CRM [attempt 1]
##[debug]Connection to CRM Established using OrganizationServiceProxy
##[debug]Updating Entity: Xrm.Framework.CI.Common.Entities.Solution
##[debug]Caught exception from task script.
##[debug]Error record:
##[debug]Set-XrmEntity : Solution patch with version 3.6.1.0 already exists. Updating patch is not supported.
##[debug]At C:\agent\_work\tools\MSCRMBuildTools\9.0.23\xRMCIFramework\9.0.0\UpdateSolutionDescriptionInCRM.ps1:62 char:1
##[debug]+ Set-XrmEntity -ConnectionString $CrmConnectionString -EntityObject $s ...
##[debug]+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##[debug]    + CategoryInfo          : NotSpecified: (:) [Set-XrmEntity], FaultException`1
##[debug]    + FullyQualifiedErrorId : System.ServiceModel.FaultException`1[[Microsoft.Xrm.Sdk.OrganizationServiceFault, Micros    oft.Xrm.Sdk, Version=9.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]],Xrm.Framework.CI.PowerShell.Cmdle    ts.SetXrmEntityCommand
##[debug] 
##[debug]Script stack trace:
##[debug]at <ScriptBlock>, C:\agent\_work\tools\MSCRMBuildTools\9.0.23\xRMCIFramework\9.0.0\UpdateSolutionDescriptionInCRM.ps1: line 62
##[debug]at <ScriptBlock>, C:\agent\_work\_tasks\MSCRMUpdateSolutionDescription_f7e23de4-4bbe-42bd-a75c-9bc939a7ca44\10.0.3\MSCRMUpdateSolutionDescription.ps1: line 48
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]at <ScriptBlock>, <No file>: line 22
##[debug]at <ScriptBlock>, <No file>: line 18
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]Exception:
##[debug]System.ServiceModel.FaultException`1[Microsoft.Xrm.Sdk.OrganizationServiceFault]: Solution patch with version 3.6.1.0 already exists. Updating patch is not supported. (Fault Detail is equal to Exception details: 
##[debug]ErrorCode: 0x8004F042
##[debug]Message: Solution patch with version 3.6.1.0 already exists. Updating patch is not supported.
##[debug]TimeStamp: 2019-10-26T05:57:30.1475486Z
##[debug]--
##[debug]Exception details: 
##[debug]ErrorCode: 0x8004F042
##[debug]Message: Solution patch with version 3.6.1.0 already exists. Updating patch is not supported.
##[debug]TimeStamp: 2019-10-26T05:57:30.1475486Z
##[debug]--
##[debug]).
##[error]Solution patch with version 3.6.1.0 already exists. Updating patch is not supported.
##[debug]Processed: ##vso[task.logissue type=error]Solution patch with version 3.6.1.0 already exists. Updating patch is not supported.
##[debug]Processed: ##vso[task.complete result=Failed]
`

**Comment by WaelHamze** [comment]
@aboodh95 did you try if you can do the same thing via UI?

What are you trying to put in the description?

**Comment by aboodh95** [comment]
Hi @WaelHamz,

I can edit the description from the UI, and once i'm creating a patch i'm trying to provide some description about this patch

**Comment by WaelHamze** [comment]
@aboodh95 should be working now
