### ISSUE TITLE
How do you Extract Solution to Source Control?

### ISSUE THREAD

**Issue by SuperSaiyanHaris** [WaelHamze/dyn365-ce-vsts-tasks#121]
Hi Wael,

Here is my extract solution step where my "Unpacked Files Folder" value is my branch in TFS:
![Build](https://user-images.githubusercontent.com/57416543/68693671-49f29500-053d-11ea-994f-a7b3b072a911.png)

The output shows that it's unpacking the files into the sources folder instead (This should be unpacking to my branch instead, right?):
![Ouput](https://user-images.githubusercontent.com/57416543/68693763-77d7d980-053d-11ea-9de7-3123519b716b.png)

Repository for the build:
![image](https://user-images.githubusercontent.com/57416543/68694176-43b0e880-053e-11ea-800a-10b8e6f99bdf.png)

Let me know if you need any additional information. I am new to these processes so bare with me haha. 

Thanks!!

**Comment by SuperSaiyanHaris** [comment]
Hi Wael, 

I have been able to successfully get my solution files into source control so ignore my above question. However, I am wondering if your tools have the capability to add new items to source control? When I do a check-in, I can see all my existing files changes, but for example, if a new entity was created and now the "Entities" folder has "New Entity" folder in it that needs to get source controlled, do I always have to manually add new items?

Thanks,

**Comment by mattp65** [comment]
Solution Packager has no knowledge of your source control, it just interacts with the local file system of the server executing it. You need to add a step to do the checkin from that workspace in the local folder to your source system. It is no different than if you run Solution Packager on you own machine, you then have to do something to get it into Source Control (Git or VSTS or whatever).

**Comment by WaelHamze** [comment]
@SuperSaiyanHaris as @mattp65 suggested the task doesn't put a dependency on a specific source control system. You can use Git commands to achieve this.
