### ISSUE TITLE
ConnectionString AuthType ClientSecret.

### ISSUE THREAD

**Issue by mathiasbl** [WaelHamze/dyn365-ce-vsts-tasks#124]
Hello,

I'm trying to use a connection string with AuthType=ClientSecret as seen [here](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/xrm-tooling/use-connection-strings-xrm-tooling-connect).
It does seem to work with your current version. This is probably part of a later release of the CrmServiceClient.

**Comment by mgr1054** [comment]
Same issue here. Did you make any progess?
