### ISSUE TITLE
Power Apps checker: output validation errors in build pipeline

### ISSUE THREAD

**Issue by mathiasbl** [WaelHamze/dyn365-ce-vsts-tasks#125]
It would be awesome if you can see the list of issues as output in your build pipeline.

**Comment by WaelHamze** [comment]
Can be easily done, have you tried to using the sarif viewer on the build to see the results in a more friendly way?

**Comment by mathiasbl** [comment]
Could you give more details? Is there a sarif viewer task?

**Comment by WaelHamze** [comment]
@mathiasbl https://marketplace.visualstudio.com/items?itemName=sariftools.sarif-viewer-build-tab

**Comment by WaelHamze** [comment]
@mathiasbl did you get a chance to check the sarif viewer?

If we were to list the issues in the build log, what information you think it would be useful. The simplest would be to output the full json but that will be a lot of information in there.

**Comment by mathiasbl** [comment]
@WaelHamze yes, I installed it. Works great! Thanks.
