### ISSUE TITLE
Issue with the MSCRM PackageDeployer task

### ISSUE THREAD

**Issue by VericaHodder** [WaelHamze/dyn365-ce-vsts-tasks#13]
Hi,
We are using the PackageDeployer toolset through AzureDevOps to deploy Dynamics 365 solutions, config and data from one Dynamics environment to another (on the same tenant). the deployment is working partially but ends with an error. (please see attached the error logs). 
When we run the solution deployment and the config and data manually using the gui tool it works with no errors. 
![errorscreenshot](https://user-images.githubusercontent.com/44467876/47565210-aa596900-d91f-11e8-96c9-f175eb2fcd50.JPG)

Error: The complex data import is complete. 
Import Failed 

[4_Microsoft.Xrm.Tooling.PackageDeployment-2018-10-26.log](https://github.com/WaelHamze/dyn365-ce-vsts-tasks/files/2519063/4_Microsoft.Xrm.Tooling.PackageDeployment-2018-10-26.log)
[4_MSCRM Portal Package Deployer.log](https://github.com/WaelHamze/dyn365-ce-vsts-tasks/files/2519064/4_MSCRM.Portal.Package.Deployer.log)

Thanks
Regards
Verica

**Comment by WaelHamze** [comment]
closing this issue, please re-open if you still getting this. I could not replicate this.

**Comment by sdeshbhratar** [comment]
Hi WaelHamze

I am getting the same issue as well. I can share my solution and import data zip file. This are sample files and runs fine within the Configuration Migration tool.

Any help is very much appreciated.
