### ISSUE TITLE
Configuration Migration Tool: new features

### ISSUE THREAD

**Issue by mathiasbl** [WaelHamze/dyn365-ce-vsts-tasks#130]
The lastest release of the Configuration Migration Tool has 2 new features in its settings:
![13615C47-F158-439A-90E3-45D3C19E9C8A](https://user-images.githubusercontent.com/16224711/70844305-66853400-1e3f-11ea-93b0-eb20824995ea.jpeg)

This is part of the schema. 
Please update the reference to the tool so we can take advantage of these new options

**Comment by WaelHamze** [comment]
@mathiasbl Yes planning to add that in the release and also include the batch parameters
