### ISSUE TITLE
MSCRM Apply Solution Upgrade task always times-out

### ISSUE THREAD

**Issue by bryder08** [WaelHamze/dyn365-ce-vsts-tasks#132]
Whenever we use this task for any of our several Dynamics 365 environments the task doesn't appear to catch feedback from the Dynamics instance that the solution upgrade has completed. Consequently it continues for a number of hours and ends up throwing a timeout error:

```
 ##[error]The request channel timed out while waiting for a reply after 02:46:40. 
Increase the timeout value passed to the call to Request or increase the SendTimeout value on the Binding.
 The time allotted to this operation may have been a portion of a longer timeout.
2019-12-16T15:21:56.3838180Z ##[section] Finishing: MSCRM Apply Solution Upgrade: XXXX (Default Disabled)
```

This is making our releases take a additional number of hours waiting for this task to timeout.
We don't want to shorten the timeouts as it may not have completed before the release moves on to do other things.

Any suggestions? Is this a bug?

**Comment by WaelHamze** [comment]
@bryder08 This task is generally very reliable for the solutions I work with. Are you running this task in Sync or Async mode?

**Comment by bryder08** [comment]
@WaelHamze We are using task version 9 which I believe doesn't have sync/async options.

**Comment by WaelHamze** [comment]
@bryder08 What version of Dynamics 365 environments do you have? Are these online? Have you tried the v10 task? If you are using online async should be supported.

**Comment by bryder08** [comment]
@WaelHamze We previously got an error with the v10 version. However, on retesting it appears to be working fine and the timeout error no longer occurs either.
Happy to close this issue.

**Comment by WaelHamze** [comment]
@bryder08 glad to hear that. Will close it. You can re-open if you hit this issue.
