### ISSUE TITLE
MSCRM Plugin Registration tool - Assembly name path is not found

### ISSUE THREAD

**Issue by Kevin-Pinero** [WaelHamze/dyn365-ce-vsts-tasks#133]
Hello,
I hope this is the right place to ask this question.

I am having an issue configuring a release pipeline with the MSCRM Plugin registration tool,
Im providing the bin content of my solution, resulting from my build pipeline, in the assembly path field and i get an error on the path specified.

![image](https://user-images.githubusercontent.com/25352361/71582095-d31f5480-2b08-11ea-9142-84779540fc29.png)

![image](https://user-images.githubusercontent.com/25352361/71582115-eb8f6f00-2b08-11ea-9a31-d8fdf5faded8.png)

Could you give more indications as to what is expected in that folder, or field ?
As well, is there a way to somehow improve the logs and the error message to have more details ?

Thank you !

**Comment by WaelHamze** [comment]
@Kevin-Pinero looks like this path may not exist. This should be the full path to the assembly

![image](https://user-images.githubusercontent.com/11046518/71693677-f8c88a00-2da4-11ea-8cc9-2b1448e76a97.png)

**Comment by Kevin-Pinero** [comment]
Oh i see, small mistake then. As it's written "Path to assembly" I did not select the file itself ...
Thanks for your reply.
