### ISSUE TITLE
MSCRM Check Solution task fails

### ISSUE THREAD

**Issue by mathiasbl** [WaelHamze/dyn365-ce-vsts-tasks#136]
Our builds starting failing in the late afternoon with the error below. Builds around noon and in the morning were still working. 

The specified module 'c:\agent\_work\tools\MSCRMBuildTools\9.1.2\Microsoft.PowerApps.Checker.PowerShell\1.0.2\Microsoft.PowerApps.Checker.PowerShell.psd1' was not loaded because no valid module file was found in any module directory.

![image](https://user-images.githubusercontent.com/16224711/71998758-7f1b1b00-3240-11ea-9906-8dc798de4070.png)

**Comment by mathiasbl** [comment]
Started failing when the MSCRM Tool Installer started with 9.1.2

![image](https://user-images.githubusercontent.com/16224711/71998923-c2758980-3240-11ea-8174-03683d5ace24.png)

**Comment by WaelHamze** [comment]
I think you need to switch to using version 11 of the checker task.

On 8 Jan 2020, at 17:00, Mathias <notifications@github.com> wrote:

﻿

Started failing when the MSCRM Tool Installer started with 9.1.2

[image]<https://user-images.githubusercontent.com/16224711/71998923-c2758980-3240-11ea-8174-03683d5ace24.png>

**Comment by mathiasbl** [comment]
Thank you. That fixed it :)

**Comment by rfontijn** [comment]
Yes, that works, thanks. However, IMHO this should be backwards compatible or have an upgraded version, so the previous version keeps working.

**Comment by WaelHamze** [comment]
@rfontijn yes everything would normally be backwards compatible and this is how everything is designed. However v10 of Checker was a very early beta/preview so it was very difficult to keep it working especially with limitation of extension size.
