### ISSUE TITLE
Connection String without Password

### ISSUE THREAD

**Issue by sohaib-ahmad** [WaelHamze/dyn365-ce-vsts-tasks#137]
How can we put a connection string without clear text passwords in Solution Export / Import tasks?

**Comment by rfontijn** [comment]
Make use of CliendId, ClientSecret having an App regsitration in Azure.

**Comment by WaelHamze** [comment]
@sohaib-ahmad you need to use variables/library and lock them so they are not visible.

https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#secret-variables

**Comment by mattp65** [comment]
You can also leverage a KeyVault in Azure to hold your password. Once you add the Azure Key Vault task to your pipeline, the secrets are available just like any other variable and can be used to build your connection string.
