### ISSUE TITLE
Task Check Solution throws exceptions

### ISSUE THREAD

**Issue by rfontijn** [WaelHamze/dyn365-ce-vsts-tasks#138]
Since Jan 8, this error is thrown when the Check Solution task is launched. The day before it worked properly. Have some things changed?

```
The specified module 'C:\agent_01\_work\tools\MSCRMBuildTools\9.1.2\Microsoft.PowerApps.Checker.PowerShell\1.0.2\Microsoft.PowerApps.Checker.PowerShell.psd1' was not loaded because no valid module file was found in any module directory.
```

**Comment by WaelHamze** [comment]
@rfontijn check this issue: https://github.com/WaelHamze/dyn365-ce-vsts-tasks/issues/136
