### ISSUE TITLE
New Request: Solution Description

### ISSUE THREAD

**Issue by carolina007** [WaelHamze/dyn365-ce-vsts-tasks#14]
Every time we build/Extract the  solution we add build/Extract date in the solution properties. Could you please add that feature.

$currentDateTime = Get-Date

#Query CRM for Solution properties
$baseSolution = Get-XrmSolution -ConnectionString $targetCrmConnectionUrl -UniqueSolutionName $solutionName

#Set new Description property for Solutions
Write-Host "Updating Solution properties..."
$baseSolution.EntityState = "Changed"
$baseSolution.Description = "Build " + $baseSolution.Version + " - Build Date: " + $currentDateTime

#Update CRM
Set-XrmEntity -ConnectionString $targetCrmConnectionUrl -EntityObject $baseSolution

**Comment by WaelHamze** [comment]
Update Solution Description Task Released to Marketplace
