### ISSUE TITLE
ImportSolution Task should not proceed with next solution within "ImportConfig.json" if prior solution fails

### ISSUE THREAD

**Issue by chmoules** [WaelHamze/dyn365-ce-vsts-tasks#145]
[importstagingconfig.txt](https://github.com/WaelHamze/dyn365-ce-vsts-tasks/files/4181592/importstagingconfig.txt)
VSO Task Import Solution config.
VSO Log of Solution Import – Search for “FaultException” to reach the Error message line.

More than solution import failure, we want to focus on why the VSO Task went to next solution instead of EXITING at that Failed solution.

Please let me know any switch/flag to set to ensure the "Import" Fails at the Failed solution itself instead of proceeding forward with next solution in the config.
[1_Run on agent.log](https://github.com/WaelHamze/dyn365-ce-vsts-tasks/files/4181638/1_Run.on.agent.log)

**Comment by WaelHamze** [comment]
@chmoules thanks for sharing the logs. This is a defect. This has been fixed and will be deployed in the next release.

**Comment by WaelHamze** [comment]
@chmoules this should be working now.
