### ISSUE TITLE
Restore Backup based on DateTime

### ISSUE THREAD

**Issue by mVermaat** [WaelHamze/dyn365-ce-vsts-tasks#146]
I want to restore a backup from a specific DateTime (a system backup, not a manual backup). I noticed that the task only allows the use of a Label. I saw the CmdLet from Microsoft does support it.

I was going to make a PR that has the added variable, however I see that Azure DevOps doesn't allow input parameters to be a DateTime. See [Schema](https://github.com/microsoft/azure-pipelines-task-lib/blob/master/tasks.schema.json).

Before spending some time of making this. @WaelHamze, what is your opinion on this?

**Comment by WaelHamze** [comment]
@mVermaat I can't see how you can achieve this with the current APIs. I couldn't find the restore point in the PS module once loaded in PS ISE.

Regarding input parameter, it would have to be a string that can be parsed into a datetime in UTC preferably. If you want to get complicated you can create a datetime control for this :)

Anyway we need the API for this first. I'll see if I can get more info on how to do this.

**Comment by mVermaat** [comment]
Awesome, thanks!

**Comment by WaelHamze** [comment]
@mVermaat Let me know how it works for you. I tried to keep it backwards compatible. So it retrieves the backup timestamp from label as the new api doesn't support restore using backupid

**Comment by mVermaat** [comment]
@WaelHamze I just included your change in my pipeline. It works great!
