### ISSUE TITLE
Authentication using Client Secret

### ISSUE THREAD

**Issue by TomasGold** [WaelHamze/dyn365-ce-vsts-tasks#147]
I cannot seem to be able to authenticate using Client Secret despite using the same connection string without an issue elsewhere. Reading @WaelHamze's [statement](https://github.com/WaelHamze/xrm-ci-framework/issues/198#issuecomment-552113344), it should be supported.

1. Has anybody successfully used [Client Secret authentication](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/xrm-tooling/use-connection-strings-xrm-tooling-connect#clientid-or-client-secret-based-authentication)?
`AuthType=ClientSecret;url={DynamicsURL};ClientId={AppId};ClientSecret={ClientSecret}`

1. Does anybody have any suggestion on how to troubleshoot?
The generic `Unable to Login to Dynamics CRM` error does not point me anywhere and I can connect with the identical connection string from my desktop.

Thanks!
Tomas

**Comment by WaelHamze** [comment]
@TomasGold can you connect with username/password successfully on that agent/pipeline?

**Comment by TomasGold** [comment]
Yes, that works fine so it does not seem to be agent/pipeline related. Any other idea?

Thanks for picking this up by the way!

**Comment by phuocle** [comment]
Just test the Ping task and it worked.

**Comment by joshcampbell191** [comment]
@TomasGold We're currently using this connection string in our environment without any issues. 

Here's our connection string as an example:
`AuthType=ClientSecret;Url=$(crm.url);ClientId=$(tenant.appId);ClientSecret=$(tenant.secret)`

Is it a task in particular or does it happen for every task? I also noticed that the 'u' from Url is lower case. Can you please try with an uppercase 'U' instead.

**Comment by TomasGold** [comment]
@joshcampbell191 Thank you for the time you took to respond. I cannot re-test it right now in the same environment but I will close this issue since multiple people confirmed this works. I am not sure why I could not make it work. Perhaps the lower case U was the root cause.
