### ISSUE TITLE
EMail Log File

### ISSUE THREAD

**Issue by carolina007** [WaelHamze/dyn365-ce-vsts-tasks#15]
We are planning to add email functionality to email log file after failure in import.  Could you please help us in using this.

https://github.com/WaelHamze/dyn365-ce-vsts-tasks/blob/master/BuildTools/Xrm.CI.Framework.BuildTools/Tasks/MSCRMImportSolution/MSCRMImportSolution.ps1

if (Test-Path "$artifactsFolder\$logFilename")
{
	Write-Host "##vso[task.uploadfile]$artifactsFolder\$logFilename"
}

**Comment by carolina007** [comment]
Thank you For Fixing this. Let me know next release date for this.

**Comment by WaelHamze** [comment]
Released to Marketplace
