### ISSUE TITLE
MSCRM Copy Instance (Preview)

### ISSUE THREAD

**Issue by sannicolao** [WaelHamze/dyn365-ce-vsts-tasks#154]
I know its preview, but i will receive in this task the following error: 

_Unable retrieve Crm Operation Status Cannot bind parameter 'Id'. Cannot convert value "" to type "System.Guid". Error: "Unrecognized Guid format."_

Could someone help me?

**Comment by WaelHamze** [comment]
@sannicolao is this happening to you all the time or in some cases? can you share a bit more details on the parameters?

Can you run the pipeline in debug mode and share the logs?

**Comment by sannicolao** [comment]
@WaelHamze : That's only happened at one day. Right now it works with the same settings, probably it was a daily bug in my area or a MS Bug. 
Thanks. I will close it.
