### ISSUE TITLE
Powershell script for Import and Exporting solutions

### ISSUE THREAD

**Issue by bfallar3** [WaelHamze/dyn365-ce-vsts-tasks#157]
Hi, can you provide guidance or document on how to start writing powershell scripts specific for Dynamics CRM importing and exporting solutions using Web API? I'm trying to make a powershell cmdlets that can be use for Jenkins.

**Comment by bfallar3** [comment]
Thanks @WaelHamze 
But this cmdlets only works for Jenkins for Windows environment, right?
Does this also work for Linux environment with Powershell plugin in Jenkins?

**Comment by WaelHamze** [comment]
@bfallar3 yes only for windows.
