### ISSUE TITLE
Need a non-empty authority

### ISSUE THREAD

**Issue by woorsty** [WaelHamze/dyn365-ce-vsts-tasks#159]
Hi,
I try to reset or restore an online 9.1 CRM in my azure pipeline.

If I use MSCRMResetOnlineInstance or MSCRMRestoreOnlineInstance, I get this error:

> ##[error]Need a non-empty authority

There is no option to set the authority in both tasks.

I have the latest version (9.14.2) installed and the used vmImage is 'windows-latest'

Those are the parameters I used (I had to censore some values):
![image](https://user-images.githubusercontent.com/15033998/76195914-939c7500-61e9-11ea-901c-76a152d880a4.png)

**Comment by WaelHamze** [comment]
ApiUrl should be in your case: https://admin.services.crm4.dynamics.com
