### ISSUE TITLE
Provision Online Instance - update Service Version "Display" dropdown to include version

### ISSUE THREAD

**Issue by stephenacrown** [WaelHamze/dyn365-ce-vsts-tasks#16]
Hi @WaelHamze 

As we (both myself and @VericaHodder) are new to Dynamics 365 and Azure DevOps, a few things have caught us out - one of which is below, and we'd like to contribute back some of our time to make some things clearer and improve things where we can as this is a great extension, and is very valuable to us and the community. Given we're coming at this fresh, I feel we could add some value here.

I have tried (unsuccessfully) to publish a local branch of this repo with the proposed minor display only changes to aid the user into which drop down box to select. I know of Dynamics only as v8.2 and v9.x, and took a while to try and figure out which one was the right drop down, and what they meant!

Here are my proposed (minor) changes that I'd like to see incorporated if that is possible please to prevent anyone else having the same issue:

**_File in question to edit:
dyn365-ce-vsts-tasks/BuildTools/Xrm.CI.Framework.BuildTools/Tasks/MSCRMProvisionOnlineInstance/task.json_**

**_Line(s):
113 and 114_**

**_Detail of request:
Add version numbers (e.g. v8.2; v9) into the displayed options_**

Current displayed options:
![image](https://user-images.githubusercontent.com/38353501/47745887-a6f61280-dc7c-11e8-889c-d30afcd5ae2b.png)

Azure DevOps GUI displayed options:
![image](https://user-images.githubusercontent.com/38353501/47746050-18ce5c00-dc7d-11e8-8097-df50d62fd358.png)

Our tenant has these as options with version detail:
![image](https://user-images.githubusercontent.com/38353501/47745915-bc6b3c80-dc7c-11e8-8f0c-df47579d443a.png)

Thank you.

Stephen

**Comment by WaelHamze** [comment]
@stephenacrown thanks a lot for your feedback. I think these descriptions were inline at the time the task was first published. I am trying to get the versions on my tenant now and get the error below. Is this still working for you?

ERROR REQUESTING Token FROM THE Authentication context,Microsoft.Xrm.OnlineManagementAPI.GetCrmServiceVersions

**Comment by stephenacrown** [comment]
Hi,

Yes still working for me - see below:

![image](https://user-images.githubusercontent.com/38353501/49101299-c4af9b00-f26d-11e8-866a-ebc1d9ec4182.png)

**Comment by WaelHamze** [comment]
Released to Marketplace
