### ISSUE TITLE
MSCRM Export Config Migration Data: Azure DevOps CICD - Export Failed

### ISSUE THREAD

**Issue by frick-brian** [WaelHamze/dyn365-ce-vsts-tasks#160]
Trying to get the Export/Pack/Import Config Migration Data working in Azure DevOps Pipelines/Releases for CICD.  We are in Dynamics 365 Version 1710 (9.1.0.13841) online.

I have created a schema file using the SDK Configuration Migration Manager tooling.  It is two entities, with maybe 20 fields each.  The schema file is like 8KB, so I do not think its related to a reported bug of schema files over 15MB.

I did not see any way to produce the schema file through CICD tooling, so I generated it manually, and then uploaded it to my repo files (first in the root, then in a dedicated folder).

When I run my release, I get the simple error 'export failed' - no additional information about what actually failed, so of course I cannot see much more there.  

I assume, and have to assume because I do not see any documentation, that the Export Configuration Migration Data task itself _should create a data.zip file_, and that I do not need to provide the data file itself (only the schema).  I am expecting the "Data File" input line to point to where the data file itself should be output to.

I have tried to feed the Schema file with a leading /, and without, in a folder and in the root, but regardless, I get the same error.

Now again, I can't tell  if it's failing on the _SCHEMA FILE_ or the _DATA FILE_ because the error is not verbose.

Any tips on this?

Below is my config of the task.  I have not yet gotten to the Pack or Import steps, so any tips or tricks that you've run into on the Pack/Import steps would be helpful as well.

![image](https://user-images.githubusercontent.com/15112935/76324977-2823d780-62bd-11ea-9c46-1812bfd04645.png)

**Comment by JamesStuder** [comment]
@frick-brian I have a feeling it's the schema file.  You can turn on debugging to get more detailed info.  Here is my debug to add more info to this:
![image](https://user-images.githubusercontent.com/1296449/76811459-eff22c80-67c7-11ea-82ae-39f448a5b7e4.png)

I too was having issues with the Schema.  First time I did it without the / and the output was looking at the C drive of the vm.  The second time was without the slash and it looked at, what appears to be the correct folder in the vm D:\a\1\s.  Not sure why the script isn't seeing the file.

**Comment by JamesStuder** [comment]
I resolved my issue of the null file.  But the export failed is still happening.  My file is null was because I have 4 branches in git and my pipelines live in the master branch.  When files are kicked off in a build process, the repository is pulled into the build source directory.  Before my call to export the config file I switch my branch in the vm to dev.  To fix this, I added a copy file task and have it copy my folder with my configuration data to the agent build directory.  This way when I switch to the dev branch the files are in a temporary location in the vm to be consumed.  The export configuration step did see my file.  But, still failed on export.  I am using the v2 (yaml) pipelines.  Here is my yaml.

Lines 1 - 2 = Using variables group to store my D365 info.
Lines 4 - 5 Pool vm since using azure pipeline hosted agent.
Lines 8 - 10 are used because I am using a build pipeline to pull down data from D365 and place them in source control.  These are needed to make that happen.
Lines 13 - 17 this is where I copy the conflagration files from the source folder (master branch) to the agent source folder in the vm.
Lines 19 - 24 this is where I prepare the git info and switch to the dev branch in the vm
Lines 26 - 30 this is where I pull the data from CRM. - ERROR HAPPENS HERE
Lines 32 - 36 this is where i push the files to dev source control
![image](https://user-images.githubusercontent.com/1296449/76813371-22068d00-67ce-11ea-9cbf-d6f172e384f4.png)

Here is the new debug log:
![image](https://user-images.githubusercontent.com/1296449/76813440-59753980-67ce-11ea-89d5-1b9605eb1ca6.png)

**Comment by JamesStuder** [comment]
Running the schema file locally with the Configuration Migration tool works.

**Comment by JamesStuder** [comment]
@frick-brian @WaelHamze This doesn't appear to be a bug in my opionion.  I finally got it working on my end.  Here is my Yaml.  What I found is you have to copy the file out of your repro using the Copy file task.  then make sure you use Data.Zip as the file name.  If you are placing it back into source control, you will need to use Git.  Again, here is my Yaml where I got it to work:
![image](https://user-images.githubusercontent.com/1296449/76886541-53776b00-6857-11ea-9c9d-a477c5618893.png)

Here is the Zip File that was committed to my source control:
![image](https://user-images.githubusercontent.com/1296449/76886604-6db14900-6857-11ea-8639-e74ff5cc7798.png)

I hope the Yaml I posted and you get upblocked on this.

**Comment by frick-brian** [comment]
Thanks for taking the time to provide all of your details.  I had been in the midst of a very complex sprint, so hadn't had time to jump back in and take a look in a few weeks...

Is there any chance you could post screenshots (redacted of course) of your configs in each step of the export/import process within CICD?  I am going to try and get it running - on a simple schema for now - to prove out the process.  Thank you in advance!

**Comment by JamesStuder** [comment]
The screenshots of the configuration are the above yaml as I am using Pipelines v2.  To see the values for the tool look at the task:MSCRMExportCMData@9.  That shows what I set to get it exported.  The git steps are used to push the solution files to the Dev Branch in our Repo.  If I miss understood please let me know and I will try to provide anything I can.

**Comment by frick-brian** [comment]
Thanks James.  I went through and re-read your posts, and your YAML, and I got it working just now.  It was only a single account with no real filtering, realtionships, etc, but!  I have now proven that I can overcome the beast of CICD config data migration :)

Thanks again for your help - very much appreciate it.  Hoping I can implement the Config Data migration into my various client environments - with specifically filtered schema files for each client.  This is going to be fun! (Seriously, much more fun than having to do it manually).

**Comment by frick-brian** [comment]
A couple of things I learned (I am still relatively new to CICD and DevOps as a whole)....

1) I was hung up on the Artifacts of the pipeline for a while.  I had it linked to a _build_ rather than the artifacts in the   Project/Repo.  Setting the Artifacts correctly helped me to solve most of my problems.

2) I am unsure if necessary or not, but I did add the "Copy Files" task to my release, and after I did that, it worked well.

3) The connection string is a bit finicky - I had posted in a previous issue report on how I resolved that, but just so it is also here, my connection string is below EXACTLY how it needs to be formatted for O365.  No quotes, no semicolons, etc...
AuthType=Office365;Username= person@microsoft.com; Password=P@$$w0rd;Url=https://myorg.crm.dynamics.com

4) I am still having a little bit of trouble understanding the Virtual Directories that are built and used during a pipeline/release in DevOps.  This is how I configured my Copy Files, Export Data, and Import data.  

_Copy Files Step_
![image](https://user-images.githubusercontent.com/15112935/78045204-a9faa400-7343-11ea-8649-c78c11d15b98.png)


_Export Config Migration Data Step_
![image](https://user-images.githubusercontent.com/15112935/78045318-cdbdea00-7343-11ea-8388-5f40465ce9c8.png)

_Import Config Migration Data Step_
![image](https://user-images.githubusercontent.com/15112935/78045387-e4644100-7343-11ea-93bf-05c64f22e459.png)

5) Here are the steps actually needed to get this to work.  The other steps are not necessary, at least if you provide your own schema file.  I am not sure if there is a way to automate the generation of the schema file(s) - but even if there was, I would think its a bit too risky to build those in an automated fashion - though I'd be glad to be proven wrong here.

![image](https://user-images.githubusercontent.com/15112935/78045002-64d67200-7343-11ea-856e-329c70ccced8.png)
