### ISSUE TITLE
##[error]The term 'D:\a\tools\MSCRMBuildTools\9.1.3\MSCRMToolsFunctions.ps1' is not recognized as the name of a cmdlet, function, script file, or operable program.

### ISSUE THREAD

**Issue by lar-mar** [WaelHamze/dyn365-ce-vsts-tasks#163]
Hi Wael,
I'm facing an issue when using the "Check solution" task.
_**##[error]The term 'D:\a\tools\MSCRMBuildTools\9.1.3\MSCRMToolsFunctions.ps1' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.**_

![image](https://user-images.githubusercontent.com/15412588/78121242-72572f00-740b-11ea-8d01-9ddf17d3c3a8.png)

![image](https://user-images.githubusercontent.com/15412588/78121375-9a469280-740b-11ea-99c1-a419c6fec786.png)

![image](https://user-images.githubusercontent.com/15412588/78121488-bb0ee800-740b-11ea-9ab8-65ccfee60caf.png)

Any idea? I think my configuration looks fine.

**Comment by WaelHamze** [comment]
@lar-mar if you use v12 of any of the tasks, these have a dependency on v12 of the tool installer task. 

So v12 task needs a minimum of v12 tool installer.

Let me know if this works.

**Comment by lar-mar** [comment]
Issues is resolved.
I just saw that the "MSCRM Tool Installer" task wasn't replaced by the new "Power DevOps Tool Installed". Instead there is a new task "Power DevOps Tool Installer" task which I have to use.

Sorry, but I found my mistake after publishing the issue.
