### ISSUE TITLE
Connection string to D365 online environment with MFA

### ISSUE THREAD

**Issue by MarkusH87** [WaelHamze/dyn365-ce-vsts-tasks#164]
Hi there

I'am using the MSCRM Tools/DevOps PowerTools to implement CI/CD for mutiple D365 instances and I just love it.

Unfortunately our admins descided to force enable MFA on all our accounts and environments.
I spent hours trying to build a working connection string, but with no luck.

I tried with interactive logins or with bypassing MFA using a client secret.
But I haven't had any luck on this.

That's why I'm asking here:
Can anybody provide a working connection string and some step-by-step hints if any Azure AD settings needs to be set or what ever.

I asume I'm not the only person facing this problem - and I would appreciate to continue using this toolbox.

Thanks in advance

Regards Markus

**Comment by WaelHamze** [comment]
@MarkusH87 have you had any luck with this?

**Comment by MarkusH87** [comment]
> @MarkusH87 have you had any luck with this?

Unfortunately not yet, but to be honest: I wasn't able to do any further tests the last couple of days.
But if you have any idea of how to get rid of this topic, I'm glad to hear them.

**Comment by gejotas** [comment]
If you add/connect a service principal to your Azure DevOps pipeline you should be able to connect with a regular connection string (ClientId / ClientSecret). This does require the service principal to be system administrator in the environment (It needs to be added as an application account and then given the sys admin role). Use the "Integrated Security=true;" and oauth option.

I haven't tested this yet as the build tools aren't available yet in our DevOps environment, but I'll get around to it next week. In any case, this is how we've automated a lot of our deployments to Azure after MFA got enforced.

**Comment by gejotas** [comment]
I've managed to test it in our environment. I'm able to both ping and export solutions with the "AuthType=ClientSecret" from multiple environments with an application registration on multiple agent pools (both hosted and private). Our environment is completely MFA enforced.

Connection string:
AuthType=ClientSecret;Url=https://{environment}.crm{#}.dynamics.com;ClientId={Application/Client Id};ClientSecret={Client Secret}

The application registration used was added as an application account to the environments.

**Comment by MarkusH87** [comment]
> Connection string:
> AuthType=ClientSecret;Url=https://{environment}.crm{#}.dynamics.com;ClientId={Application/Client Id};ClientSecret={Client Secret}
> 
> The application registration used was added as an application account to the environments.

Thanks for your answer, I created the connection string according your example.
When using the connection string in different tools I recieve an error about "anonymous login not allowed".
I think I'm missing the part with the application account you mentioned.
What exactly is the point with this?

Thanks

**Comment by gejotas** [comment]
> > Connection string:
> > AuthType=ClientSecret;Url=https://{environment}.crm{#}.dynamics.com;ClientId={Application/Client Id};ClientSecret={Client Secret}
> > The application registration used was added as an application account to the environments.
> 
> Thanks for your answer, I created the connection string according your example.
> When using the connection string in different tools I recieve an error about "anonymous login not allowed".
> I think I'm missing the part with the application account you mentioned.
> What exactly is the point with this?
> 
> Thanks

2 things are needed:
- App registration in Azure, this provides the ClientId and ClientSecret.
- Application Account in the PowerPlatform environment.

Adding application accounts in the PowerPlatform:
1. Advanced Settings -> Security -> Users
2. On the page where it now says "Users", click on the expansion symbol to get a whole list of views. From this list select "Application Users".
3. Create a new Application User. You'll have to enter a few pieces of info such as email, name and an application Id. The application id is the ClientId from the app registration in Azure.
4. Assign the newly created application user to a role.

In the environments in which I've tested I added one of the Azure DevOps service principals as application user to the environment.

**Comment by MarkusH87** [comment]
@gejotas 
Thanks for the dummy-explanation: I was able to get the sollution export by DevOps up and running and bypassing MFA.

Thanks
