### ISSUE TITLE
MSCRM Build Tool

### ISSUE THREAD

**Issue by kimomar1102** [WaelHamze/dyn365-ce-vsts-tasks#169]
I have written a full CI/CD using the previous version of MSCRM Build Tool, do I need to change everything to this version (Power DevOps Tool)?

**Comment by kimomar1102** [comment]
What will happen to the CI/CD pipelines for the previous version of MSCRM Build Tools?

**Comment by WaelHamze** [comment]
@kimomar1102 the previous pipelines should continue to work as they were using tasks with versions < 12. Note however tasks with versions < 12 will not be updated.

If you find yourself needing any features from v12 then you should be able to easily switch your existing pipeline to use v12

**Comment by kimomar1102** [comment]
@WaelHamze Thank you very much! Congrats on this new release!
