### ISSUE TITLE
PowerShell Script Path

### ISSUE THREAD

**Issue by jblaseske** [WaelHamze/dyn365-ce-vsts-tasks#170]
I notice the new (12.0.7) version of tools installs to a cached directory in Azure DevOps that I can't inspect.  I just need to know how to call one of the pre-built scripts:  GetPluginRegistration.ps1 in order to produce a plugin registration map.  Can someone help with this?

**Comment by WaelHamze** [comment]
@jblaseske I should you download the scripts from the PowerShell Gallery: https://www.powershellgallery.com/packages/Xrm.Framework.CI.PowerShell.Cmdlets/9.1.0.1

**Comment by jblaseske** [comment]
Sorry I gave the wrong impression.  I have downloaded the Gallery and can call the script locally with success.  I am merely looking for the correct path/command to invoke the script from an Azure DevOps pipeline PowerShell cmd, once I have run the tools install step.

**Comment by WaelHamze** [comment]
@jblaseske you will need to download the module from the gallery or nuget in your DevOps pipeline. There is no fixed path to the script as this is dynamically changing based on the version so I would not rely on it.
