### ISSUE TITLE
Build Task Check solution

### ISSUE THREAD

**Issue by lar-mar** [WaelHamze/dyn365-ce-vsts-tasks#172]
The build task "Check solution" stores the result of the solution check in a zip file in the root folder of my repo.

Questions:
1. How can I define the folder the zip file is stored in? 
2. I would rather like to publish the *.sarif file contained in the zip file as pipeline artifact so it can be shown in a "SCANS" tab for each pipeline execution using the extension "Sarif Viewer Build tab".
![image](https://user-images.githubusercontent.com/15412588/79557825-8786bb80-80a3-11ea-8c39-e3a9195390d5.png) Of course I could download and unzip the zip file and publish the *.sarif file but I would be excited if this could be defined in the configuration of the "Check solution" build task.

**Comment by WaelHamze** [comment]
@lar-mar there is a parameter in the task "Results Variable Name" you can set this to a pipeline variable. At the end of the task execution, this variable should contain the path to the zip file.

**Comment by lar-mar** [comment]
@WaelHamze 
I have seen and used this variable. 

I'm wondering if it is possible to avoid storing the zip file in my repo. I do not want to have it there. I  would like to decide by my own which files are commited to my repo.
