### ISSUE TITLE
Import config data issue

### ISSUE THREAD

**Issue by lar-mar** [WaelHamze/dyn365-ce-vsts-tasks#175]
Hi @WaelHamze,

I'm struggling with an issue when importing configuration migration data.

I defined a schema with certain entities and fields using the configuration migration utility. The schema is valid based on the tool.

I set up a dedicated pipeline for this scenario using your build tasks:
![image](https://user-images.githubusercontent.com/15412588/79832539-ef8e1800-83a9-11ea-8362-cf826fdec425.png)

`  name: Azure Pipelines
  demands: powershell

#Your build pipeline references an undefined variable named ‘builddomain’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references an undefined variable named ‘dynConnectionString’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references an undefined variable named ‘hotfixdomain’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references an undefined variable named ‘dynConnectionString’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972

steps:
- task: WaelHamze.xrm-ci-framework-build-tasks.MSCRMToolInstaller.MSCRMToolInstaller@12
  displayName: 'Power DevOps Tool Installer'

- task: jessehouwing.jessehouwing-vsts-variable-tasks.vsts-variable-set.VariableSetTask@1
  displayName: 'Set variable: dyndomain'
  inputs:
    VariableName: dyndomain
    Value: '$(builddomain)'

- task: WaelHamze.xrm-ci-framework-build-tasks.MSCRMExportCMData.MSCRMExportCMData@12
  displayName: 'Export Configuration Migration Data'
  inputs:
    crmConnectionString: '$(dynConnectionString)'
    schemaFile: 'schemafiles_configurationmigration/schemas.xml'
    dataFile: '$(Build.ArtifactStagingDirectory)\configurationdata.zip'
    crmConnectionTimeout: 10

- task: jessehouwing.jessehouwing-vsts-variable-tasks.vsts-variable-set.VariableSetTask@1
  displayName: 'Set variable: dyndomain'
  inputs:
    VariableName: dyndomain
    Value: '$(hotfixdomain)'

- task: WaelHamze.xrm-ci-framework-build-tasks.MSCRMImportCMData.MSCRMImportCMData@12
  displayName: 'Import Configuration Migration Data'
  inputs:
    crmConnectionString: '$(dynConnectionString)'
    dataFile: '$(Build.ArtifactStagingDirectory)\configurationdata.zip'
    enabledBatchMode: true
    logsDirectory: '$(Build.ArtifactStagingDirectory)\'

- task: PublishPipelineArtifact@1
  displayName: 'Publish Pipeline Artifact'
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)\'
    artifact: drop`

**Issue:**
The configuration migration data contain an entity "Country" with some migration data I want to transfer to other environments.
When using the pipeline no records are created or updated for this entity. I tried your most current task version .12 as well as the one before .9. Does not work. All other entities which are part of the config data work fine.

I used the pipeline artifact "configurationdata.zip" and imported the data via configuration migration utility (version 4.0.0.12) and the entity "Country" was updated properly.
[configurationdata.zip](https://github.com/WaelHamze/dyn365-ce-vsts-tasks/files/4508111/configurationdata.zip)

Attached are both logfiles and it seems there is anything different when using the "Import Configuration Migration Data" build task than using the configuration utility directly.
[ImportDataDetailLog - ConfigMigTool.log](https://github.com/WaelHamze/dyn365-ce-vsts-tasks/files/4508109/ImportDataDetailLog.-.ConfigMigTool.log)
[ImportDataDetailLog - Pipeline.log](https://github.com/WaelHamze/dyn365-ce-vsts-tasks/files/4508110/ImportDataDetailLog.-.Pipeline.log)

Do you have an idea?

**Comment by lar-mar** [comment]
@WaelHamze 
I did some further analysis and could determine the "Batch Mode" as root cause. As soon as I disabled the batch mode all data were imported as expected.
What I'm still struglling with is that many entities are imported fine with enabled batch mode.

For now I disable the batch mode in my pipelines and accept the worse performance.

**Comment by WaelHamze** [comment]
@lar-mar thanks for sharing. Good to know. I think the batch more is probably something to do with the SDK itself. I'll let you know if I manage to use it successfully.
