### ISSUE TITLE
Import Solution Task fails with timeout error if the solution contains changes to business unit entity

### ISSUE THREAD

**Issue by parvezghumra** [WaelHamze/dyn365-ce-vsts-tasks#178]
Hi @WaelHamze,

We are finding that the MSCRM Import Solution task fails if the solution contains any changes to the out of the box Business Unit entity. For example, simply adding a custom Two Options field to the Business Unit entity. I have attached the error log [here](https://github.com/WaelHamze/dyn365-ce-vsts-tasks/files/4573922/tasklog_30.2.log)
 and have also verified that no other solution imports are being attempted on that environment at the same time. Note that the solution import completes successfully as expected if run manually through the Dynamics 365 CE user interface.

What I have tried so far:
1. Run the task in synchronous mode rather than asynchronous. This still fails with the same error
2. Increased the timeout wait period. This makes no difference and the task still seems to fail roughly after 10 minutes.

Thanks,
Parvez

**Comment by WaelHamze** [comment]
@parvezghumra are you still facing issue? Did you try to raise this as an issue with the vendor?

The task is just calling the import API so this could be a defect in the backend. I believe there are some slight differences between importing from UI and SDK (i.e. caching etc...)

**Comment by parvezghumra** [comment]
@WaelHamze Thanks for the response. 

Yes, after raising a support case with Microsoft, they investigated and acknowledged this to be a defect in the product. They don't have an ETA for a fix yet, but have agreed to keep me posted on it's status every 2 weeks.

Thanks for the help
