### ISSUE TITLE
Error backing up 8.2 Organisation (Dynamics Online)

### ISSUE THREAD

**Issue by namurdock** [WaelHamze/dyn365-ce-vsts-tasks#19]
Hi, I am receiving the following error when the Backup task runs in VSTS:

> 2018-11-08T11:58:39.0393749Z ##[debug]Entering BackupCRMOnlineInstance.ps1
> 2018-11-08T11:58:39.0426165Z ##[debug]ApiUrl = https://admin.services.crm4.dynamics.com
> 2018-11-08T11:58:39.0460974Z ##[debug]Username = xxxxxxxxxxxxxxxxxx
> 2018-11-08T11:58:39.3812544Z ##[debug]InstanceName = xxxxxxxxxxxx
> 2018-11-08T11:58:39.3902425Z ##[debug]BackupLabel = xxxxxxxxxxx
> 2018-11-08T11:58:39.3904277Z ##[debug]BackupNotes = 
> 2018-11-08T11:58:39.4069920Z ##[debug]IsAzureBackup = False
> 2018-11-08T11:58:39.4070831Z ##[debug]ContainerName = 
> 2018-11-08T11:58:39.4071444Z ##[debug]StorageAccountKey = 
> 2018-11-08T11:58:39.4072005Z ##[debug]StorageAccountName = 
> 2018-11-08T11:58:39.4072547Z ##[debug]WaitForCompletion = True
> 2018-11-08T11:58:39.4073161Z ##[debug]SleepDuration = 5
> 2018-11-08T11:58:39.4073712Z ##[debug]PSModulePath = D:\_work\tools\MSCRMBuildTools\9.0.3\OnlineManagementAPI\1.0.0
> 2018-11-08T11:58:39.4183271Z ##[debug]Script Path: D:\_work\tools\MSCRMBuildTools\9.0.3\xRMCIFramework\9.0.0
> 2018-11-08T11:58:39.4378853Z ##[debug]Current Security Protocol: Ssl3, Tls
> 2018-11-08T11:58:39.4552740Z ##[debug]Modified Security Protocol: Ssl3, Tls, Tls11, Tls12
> 2018-11-08T11:58:39.4588871Z ##[debug]Importing Online Management Module: D:\_work\tools\MSCRMBuildTools\9.0.3\OnlineManagementAPI\1.0.0\Microsoft.Xrm.OnlineManagementAPI.dll
> 2018-11-08T11:58:39.4617436Z ##[debug]Loading module from path 'D:\_work\tools\MSCRMBuildTools\9.0.3\OnlineManagementAPI\1.0.0\Microsoft.Xrm.OnlineManagementAPI.dll'.
> 2018-11-08T11:58:39.5777464Z ##[debug]Importing cmdlet 'New-CrmAdminModeSetting'.
> 2018-11-08T11:58:39.5803964Z ##[debug]Importing cmdlet 'Get-CrmInstance'.
> 2018-11-08T11:58:39.5830835Z ##[debug]Importing cmdlet 'New-CrmInstanceInfo'.
> 2018-11-08T11:58:39.5858116Z ##[debug]Importing cmdlet 'New-CrmBackupInfo'.
> 2018-11-08T11:58:39.5884881Z ##[debug]Importing cmdlet 'Backup-CrmInstance'.
> 2018-11-08T11:58:39.5911355Z ##[debug]Importing cmdlet 'Get-CrmCurrencies'.
> 2018-11-08T11:58:39.5940845Z ##[debug]Importing cmdlet 'Get-CrmInstanceBackup'.
> 2018-11-08T11:58:39.5967430Z ##[debug]Importing cmdlet 'Get-CrmInstanceBackups'.
> 2018-11-08T11:58:39.6003678Z ##[debug]Importing cmdlet 'Get-CrmInstances'.
> 2018-11-08T11:58:39.6029703Z ##[debug]Importing cmdlet 'Get-CrmInstanceTypes'.
> 2018-11-08T11:58:39.6056386Z ##[debug]Importing cmdlet 'Get-CrmLanguages'.
> 2018-11-08T11:58:39.6083396Z ##[debug]Importing cmdlet 'Get-CrmOperationStatus'.
> 2018-11-08T11:58:39.6110071Z ##[debug]Importing cmdlet 'Get-CrmServiceVersions'.
> 2018-11-08T11:58:39.6137692Z ##[debug]Importing cmdlet 'Get-CrmTemplates'.
> 2018-11-08T11:58:39.6172908Z ##[debug]Importing cmdlet 'New-CrmInstance'.
> 2018-11-08T11:58:39.6200542Z ##[debug]Importing cmdlet 'Restore-CrmInstance'.
> 2018-11-08T11:58:39.6227479Z ##[debug]Importing cmdlet 'Disable-CrmAdminMode'.
> 2018-11-08T11:58:39.6257527Z ##[debug]Importing cmdlet 'Enable-CrmAdminMode'.
> 2018-11-08T11:58:39.6284036Z ##[debug]Importing cmdlet 'Remove-CrmInstance'.
> 2018-11-08T11:58:39.6311898Z ##[debug]Importing cmdlet 'Remove-CrmManagementApp'.
> 2018-11-08T11:58:39.6338058Z ##[debug]Importing cmdlet 'Disable-CrmManagementApp'.
> 2018-11-08T11:58:39.6362532Z ##[debug]Importing cmdlet 'Enable-CrmManagementApp'.
> 2018-11-08T11:58:39.6389439Z ##[debug]Importing cmdlet 'Get-CrmInstanceType'.
> 2018-11-08T11:58:39.6417469Z ##[debug]Importing cmdlet 'Get-CrmManagementApp'.
> 2018-11-08T11:58:39.6444655Z ##[debug]Importing cmdlet 'Get-CrmManagementApps'.
> 2018-11-08T11:58:39.6472263Z ##[debug]Importing cmdlet 'New-CrmManagementApp'.
> 2018-11-08T11:58:39.6509214Z ##[debug]Imported Online Management Module
> 2018-11-08T11:58:39.6708347Z ##[debug]Entering OnlineInstanceFunctions.ps1
> 2018-11-08T11:58:39.6734381Z ##[debug]Leaving OnlineInstanceFunctions.ps1
> 2018-11-08T11:58:39.6848321Z ##[debug]Connecting to API server: https://admin.services.crm4.dynamics.com/
> 2018-11-08T11:58:39.9957693Z ##[debug]Entering GetCrmInstances - ProcessRecord
> 2018-11-08T11:58:39.9993939Z ##[debug]Executing GetCrmInstances
> 2018-11-08T11:58:40.5752106Z ##[debug]Requesting Authentication - Start
> 2018-11-08T11:58:40.5798183Z ##[debug]Requesting Authority From server - Start
> 2018-11-08T11:58:40.6895327Z ##[debug]Requesting Authority From server - Finished : 00:00:00.1089584
> 2018-11-08T11:58:42.4971859Z ##[debug]Requesting Authentication - Completed : 00:00:01.9281283
> 2018-11-08T11:58:43.8590350Z ##[debug]Exiting GetCrmInstances - ProcessRecord : 00:00:03.8603934
> 2018-11-08T11:58:43.8697208Z Backing up instance nos-sandbox  + ed522186-f1e8-4ee5-a3cb-e13a9c320d1c
> 2018-11-08T11:58:43.8797693Z ##[debug]Entering CrmBackupInfo - ProcessRecord
> 2018-11-08T11:58:43.8822950Z ##[debug]Executing CrmBackupInfo
> 2018-11-08T11:58:43.8849099Z ##[debug]Exiting CrmBackupInfo - ProcessRecord : 00:00:00.0025292
> 2018-11-08T11:58:43.8903373Z ##[debug]Connecting to API server: https://admin.services.crm4.dynamics.com/
> 2018-11-08T11:58:43.8942036Z ##[debug]Entering BackupCrmInstance - ProcessRecord
> 2018-11-08T11:58:43.8968338Z ##[debug]Executing BackupCrmInstance
> 2018-11-08T11:58:43.9759552Z ##[debug]Requesting Authentication - Start
> 2018-11-08T11:58:43.9784444Z ##[debug]Requesting Authority From server - Start
> 2018-11-08T11:58:43.9881748Z ##[debug]Requesting Authority From server - Finished : 00:00:00.0088542
> 2018-11-08T11:58:44.2334234Z ##[debug]Requesting Authentication - Completed : 00:00:00.2574935
> 2018-11-08T11:58:44.5561143Z ##[debug]Failed GetCrmCurrencys - ProcessRecord : 00:00:00.6578509
> 2018-11-08T11:58:44.6490080Z ##[debug]Message: Operation returned an invalid status code 'InternalServerError'
> 2018-11-08T11:58:44.6518586Z ##[debug]Source	: Xrm.Online.Admin.Client
> 2018-11-08T11:58:44.6539918Z ##[debug]Method	: MoveNext
> 2018-11-08T11:58:44.6563322Z ##[debug]Date	: 11/8/2018
> 2018-11-08T11:58:44.6580979Z ##[debug]Time	: 11:58:44 AM
> 2018-11-08T11:58:44.6603203Z ##[debug]Error	: Operation returned an invalid status code 'InternalServerError'
> 2018-11-08T11:58:44.6626350Z ##[debug]Stack Trace	: at Microsoft.Xrm.Services.Admin.Client.D365CEAdminClient.<BackupInstanceWithHttpMessagesAsync>d__28.MoveNext()
> 2018-11-08T11:58:44.6648481Z ##[debug]--- End of stack trace from previous location where exception was thrown ---
> 2018-11-08T11:58:44.6669684Z ##[debug]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> 2018-11-08T11:58:44.6690484Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> 2018-11-08T11:58:44.6712415Z ##[debug]   at Microsoft.Xrm.Services.Admin.Client.D365CEAdminClientExtensions.<BackupInstanceAsync>d__5.MoveNext()
> 2018-11-08T11:58:44.6733874Z ##[debug]--- End of stack trace from previous location where exception was thrown ---
> 2018-11-08T11:58:44.6754086Z ##[debug]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> 2018-11-08T11:58:44.6775444Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> 2018-11-08T11:58:44.6800726Z ##[debug]   at Microsoft.Xrm.Services.Admin.Client.D365CEAdminClientExtensions.BackupInstance(ID365CEAdminClient operations, NewInstanceBackup backupInfo)
> 2018-11-08T11:58:44.6822195Z ##[debug]   at Microsoft.Xrm.OnlineManagementAPI.BackupCrmInstance.ProcessRecord()
> 2018-11-08T11:58:44.6843619Z ##[debug]======================================================================================================================
> 2018-11-08T11:58:44.6867401Z ##[debug]
> 2018-11-08T11:58:44.8986080Z ##[debug]Caught exception from task script.
> 2018-11-08T11:58:44.9033785Z ##[debug]Error record:
> 2018-11-08T11:58:45.0106027Z ##[debug]Backup-CrmInstance : Operation returned an invalid status code 'InternalServerError'
> 2018-11-08T11:58:45.0121829Z ##[debug]At D:\_work\tools\MSCRMBuildTools\9.0.3\xRMCIFramework\9.0.0\BackupOnlineInstance.ps1:75 char:14
> 2018-11-08T11:58:45.0143770Z ##[debug]+ ... operation = Backup-CrmInstance -ApiUrl $ApiUrl -BackupInfo $backupInf ...
> 2018-11-08T11:58:45.0164051Z ##[debug]+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 2018-11-08T11:58:45.0185053Z ##[debug]    + CategoryInfo          : NotSpecified: (:) [Backup-CrmInstance], HttpOperationException
> 2018-11-08T11:58:45.0203504Z ##[debug]    + FullyQualifiedErrorId : Microsoft.Rest.HttpOperationException,Microsoft.Xrm.OnlineManagementAPI.BackupCrmInstanc    e
> 2018-11-08T11:58:45.0220227Z ##[debug] 
> 2018-11-08T11:58:45.0246686Z ##[debug]Script stack trace:
> 2018-11-08T11:58:45.0295944Z ##[debug]at <ScriptBlock>, D:\_work\tools\MSCRMBuildTools\9.0.3\xRMCIFramework\9.0.0\BackupOnlineInstance.ps1: line 75
> 2018-11-08T11:58:45.0311371Z ##[debug]at <ScriptBlock>, D:\_work\_tasks\MSCRMBackupOnlineInstance_0c3e661c-d316-443e-9a77-470989da8e29\10.0.1\MSCRMBackupOnlineInstance.ps1: line 47
> 2018-11-08T11:58:45.0330768Z ##[debug]at <ScriptBlock>, <No file>: line 1
> 2018-11-08T11:58:45.0348200Z ##[debug]at <ScriptBlock>, <No file>: line 22
> 2018-11-08T11:58:45.0778164Z ##[debug]at <ScriptBlock>, <No file>: line 18
> 2018-11-08T11:58:45.0797583Z ##[debug]at <ScriptBlock>, <No file>: line 1
> 2018-11-08T11:58:45.0824437Z ##[debug]Exception:
> 2018-11-08T11:58:45.0887244Z ##[debug]Microsoft.Rest.HttpOperationException: Operation returned an invalid status code 'InternalServerError'
> 2018-11-08T11:58:45.0906707Z ##[debug]   at Microsoft.Xrm.OnlineManagementAPI.BackupCrmInstance.ProcessRecord()
> 2018-11-08T11:58:45.0927428Z ##[debug]   at System.Management.Automation.CommandProcessor.ProcessRecord()
> 2018-11-08T11:58:45.1304717Z ##[error]Operation returned an invalid status code 'InternalServerError'
> 2018-11-08T11:58:45.1314285Z ##[debug]Processed: ##vso[task.logissue type=error]Operation returned an invalid status code 'InternalServerError'
> 2018-11-08T11:58:45.1334123Z ##[debug]Processed: ##vso[task.complete result=Failed]

Any ideas? I am using the latest versions of the tasks from Marketplace. Do I just need to downgrade my task version? (I would just try it but i don't have a system that i can try adhoc release on at the moment).

**Comment by stephenacrown** [comment]
Hi @namurdock 

This may be related to Issue #167 on the "xrm-ci-framework" repo:

https://github.com/WaelHamze/xrm-ci-framework/issues/167

Definitely the same error as we're seeing. 

Have you tried manually with powershell on your laptop/desktop, and do you get the same error?

Suggest logging a case/call with Microsoft if it is still an issue for you when manually running the backup via powershell/api.

I note you're attempting to backup Dyn365 8.2 and I was attempting v9, but the error is the same.

Stephen

**Comment by namurdock** [comment]
Thanks for the heads up @stephenacrown . i will try locally, but this in line with other things that that have happened across our sites recently. i.e. additional entity metadata flags like the one for MS teams causing deployments from onpremise to online to fail etc. Hopefully when they start auto updating there will be less breaking changes.

**Comment by WaelHamze** [comment]
@namurdock closing this issue as there not much I can do on this. It error seems to be coming from CRM API.

@stephenacrown thx for spotting this.
