### ISSUE TITLE
PowerDevOps Apply Solution Timeout/Fail

### ISSUE THREAD

**Issue by frick-brian** [WaelHamze/dyn365-ce-vsts-tasks#191]
I am not sure this is the right spot to post this - but I couldn't find a specific repo for the PowerDevOps tooling.

Basically, the apply solution upgrade step never finishes in my release pipelines.  The solution gets updated (verified in UI - old version deleted, new version in solution list).  But this will hang for 30, 40, 50 minutes without failing, timing out, or anything - it just spins until I cancel it.  

Any idea whats going on with this?

Note: I am still using the old Power Apps steps in some of my releases, I do not think that is related, but I haven't had time to update the releases yet.  I do have some other releases that use only the new PowerDevOps tasks, and nothing that is EOL - so I am hopeful to run those pipes today and see if I have any better results.

Here is the version of Apply Solution Upgrade I am using:

2020-07-01T14:24:33.8937083Z ##[section]Starting: Apply Solution: XYZ
2020-07-01T14:24:33.9074913Z ==============================================================================
2020-07-01T14:24:33.9075260Z Task         : Apply Solution Upgrade
2020-07-01T14:24:33.9075654Z Description  : Applies a solution upgrade after solution is import using stage for upgrade option
2020-07-01T14:24:33.9076000Z Version      : 12.0.1
2020-07-01T14:24:33.9076266Z Author       : Wael Hamze
2020-07-01T14:24:33.9076550Z Help         : This task invokes DeleteAndPromoteRequest
2020-07-01T14:24:33.9076922Z ==============================================================================
**2020-07-01T14:24:34.6758294Z Solution Upgrade Starting.
2020-07-01T14:56:55.6371674Z ##[error]The operation was canceled.**
2020-07-01T14:56:55.6377818Z ##[section]Finishing: Apply Solution: XYZ

Here is the build pipe:
![image](https://user-images.githubusercontent.com/15112935/86266174-cf8d8880-bb92-11ea-9eee-da5daec028b5.png)

Here is the import options for the managed solution:
![image](https://user-images.githubusercontent.com/15112935/86266234-e3d18580-bb92-11ea-828a-71408c373d90.png)

And here is the Apply Solution Task config
![image](https://user-images.githubusercontent.com/15112935/86266309-06639e80-bb93-11ea-8b07-427f9fe929f8.png)

**Comment by frick-brian** [comment]
@WaelHamze  thanks for the tip.  I will give it a whirl.  Timeout is 900 - 15 mins, it usually completes the solution upgrade in about 10 minutes, but then times out (returns a failure in CICD) sometime between 30-60 mins.

I will report back after my next round of pushes with Async ticked.  Thanks again.

**Comment by frick-brian** [comment]
First attempt worked for me.  Now, strangely enough, the Import step continues to timeout, but I will tinker with increasing the timeout and using async there as well (it's a big solution).

Appreciate the input, I will keep an eye on this and post another issue if there is anything going wrong.  Thanks!

**Comment by saiankith-explorer** [comment]
@WaelHamze I faced this issue but it installed another solution called upgrade but the DeleteandPromote Action did not occur for me. I created a new task #195 Can you please guide me here. Thank you very much
