### ISSUE TITLE
Ping - Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by craig-lund** [WaelHamze/dyn365-ce-vsts-tasks#199]
Just today some pipeline tasks are getting the following error. 

![image](https://user-images.githubusercontent.com/54556910/89055654-a0904100-d30f-11ea-9efc-8938eb336e82.png)

I have added the connection string manually, through the "link" variable, and as a secret custom variable. 

I use the same task in other pipelines without error. 

I created a new pipeline and just added the tool installer and ping and it gives the same error.

**Comment by fouquetm** [comment]
I think it's a secret character issues. I got the same error with a " character.

**Comment by WaelHamze** [comment]
@craig-lund still need any help with this?

**Comment by kashanico** [comment]
I'm having the same issue @WaelHamze  trying to export.
I'm using ClientSecret Auth. I've tried directly entering the clientsecret as well and get the same issue.

`##[debug]=> True
##[debug]Result: True
Starting: MSCRMExportSolution
==============================================================================
Task         : Export Solution
Description  : Exports a PowerApps/CDS/Dynamics 365 Solution from the source environment
Version      : 12.0.4
Author       : Wael Hamze
Help         : This task uses [ExportSolutionRequest](https://docs.microsoft.com/en-us/dotnet/api/microsoft.crm.sdk.messages.exportsolutionrequest?view=dynamics-general-ce-9)
==============================================================================
##[debug]VstsTaskSdk 0.10.0 commit 787a46ec0a2df5b4d12c2e801bd3f319975c054c
##[debug]Entering MSCRMExportSolution.ps1
##[debug]INPUT_CRMCONNECTIONSTRING: 'AuthType=ClientSecret;url=covid-take5-dev.crm3.dynamics.com;ClientId=91c3c442-33bf-41dd-a3d6-1a31a265a4de;ClientSecret=***'
##[debug]INPUT_SOLUTIONNAME: 'CovidStatus'
##[debug]INPUT_EXPORTMANAGED: 'false'
##[debug] Converted to bool: False
##[debug]INPUT_EXPORTUNMANAGED: 'true'
##[debug] Converted to bool: True
##[debug]INPUT_INCLUDEVERSIONINSOLUTIONFILE: 'false'
##[debug] Converted to bool: False
##[debug]INPUT_TARGETVERSION (empty)
##[debug]INPUT_INCLUDEVERSIONINSOLUTIONFILE: 'false'
##[debug] Converted to bool: False
##[debug]INPUT_OUTPUTPATH: 'D:\a\1\b\solutionFiles\CovidStatus'
##[debug]INPUT_CRMCONNECTIONTIMEOUT: '120'
##[debug] Converted to int: 120
##[debug]INPUT_EXPORTAUTONUMBERINGSETTINGS: 'false'
##[debug] Converted to bool: False
##[debug]INPUT_EXPORTCALENDARSETTINGS: 'false'
##[debug] Converted to bool: False
##[debug]INPUT_EXPORTCUSTOMIZATIONSETTINGS: 'false'
##[debug] Converted to bool: False
##[debug]INPUT_EXPORTEMAILTRACKINGSETTINGS: 'false'
##[debug] Converted to bool: False
##[debug]INPUT_EXPORTEXTERNALAPPLICATIONS: 'false'
##[debug] Converted to bool: False
##[debug]INPUT_EXPORTGENERALSETTINGS: 'false'
##[debug] Converted to bool: False
`

**Comment by craig-lund** [comment]
I found the issue was white space in the URL.. 100% my error.

**Comment by WaelHamze** [comment]
@craig-lund thanks for sharing. I will close this case now.
