### ISSUE TITLE
Feature Request: Show Progress for Import/Export

### ISSUE THREAD

**Issue by s-bauer** [WaelHamze/dyn365-ce-vsts-tasks#20]
Hey, it would be nice to add an option to the Import/Export Solution tasks, which periodically displays (writes to console) the status of the import/export job until it finished.

**Comment by WaelHamze** [comment]
The SDK doesn't support progress of solution export.

We could add this to the import.

This is available by the way if you choose importing using Async mode and set system.debug = true in your pipline

**Comment by WaelHamze** [comment]
Released to Marketplace

**Comment by WaelHamze** [comment]
Note you will need to use v 11.0 of the Solution Import Task and set system.debug pipeline variable to true if you want to see the progress.

**Comment by bwmodular** [comment]
Thanks for this - very useful to get this output when you otherwise might suspect that your release has stalled.
