### ISSUE TITLE
Facing Issue while connecting to CRM by using OAuth based Connection string in Import Solution Using Config task

### ISSUE THREAD

**Issue by SnehaSoma** [WaelHamze/dyn365-ce-vsts-tasks#207]
I'm getting below error while using Import Solution using config:

Error:
2020-09-07T13:39:52.7049443Z ##[warning]ERROR REQUESTING Token FROM THE Authentication context - General ADAL Error
Federated service at https://msft.sts.microsoft.com/adfs/services/trust/2005/usernamemixed returned error: ID3242: The security token could not be authenticated or authorized. => Response status code does not indicate success: 500 (InternalServerError). => <s:Envelope xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns:a="http://www.w3.org/2005/08/addressing" xmlns:u="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"><s:Header><a:Action s:mustUnderstand="1">http://www.w3.org/2005/08/addressing/soap/fault</a:Action><a:RelatesTo>urn:uuid:6435e75c-1fea-489d-89bf-389eeebeb18e</a:RelatesTo><o:Security s:mustUnderstand="1" xmlns:o="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"><u:Timestamp u:Id="_0"><u:Created>2020-09-07T13:39:52.482Z</u:Created><u:Expires>2020-09-07T13:44:52.482Z</u:Expires></u:Timestamp></o:Security></s:Header><s:Body><s:Fault><s:Code><s:Value>s:Sender</s:Value><s:Subcode><s:Value xmlns:a="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">a:FailedAuthentication</s:Value></s:Subcode></s:Code><s:Reason><s:Text xml:lang="en-US">ID3242: The security token could not be authenticated or authorized.</s:Text></s:Reason></s:Fault></s:Body></s:Envelope>: Unknown errorUnable to connect to CRM: Response status code does not indicate success: 500 (InternalServerError).
Federated service at https://msft.sts.microsoft.com/adfs/services/trust/2005/usernamemixed returned error: ID3242: The security token could not be authenticated or authorized. => Response status code does not indicate success: 500 (InternalServerError). => <s:Envelope xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns:a="http://www.w3.org/2005/08/addressing" xmlns:u="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"><s:Header><a:Action s:mustUnderstand="1">http://www.w3.org/2005/08/addressing/soap/fault</a:Action><a:RelatesTo>urn:uuid:6435e75c-1fea-489d-89bf-389eeebeb18e</a:RelatesTo><o:Security s:mustUnderstand="1" xmlns:o="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"><u:Timestamp u:Id="_0"><u:Created>2020-09-07T13:39:52.482Z</u:Created><u:Expires>2020-09-07T13:44:52.482Z</u:Expires></u:Timestamp></o:Security></s:Header><s:Body><s:Fault><s:Code><s:Value>s:Sender</s:Value><s:Subcode><s:Value xmlns:a="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">a:FailedAuthentication</s:Value></s:Subcode></s:Code><s:Reason><s:Text xml:lang="en-US">ID3242: The security token could not be authenticated or authorized.</s:Text></s:Reason></s:Fault></s:Body></s:Envelope>: Unknown errorUnable to Login to Dynamics CRM
Unable to Login to Dynamics CRM

Connection String Format:
Url=https://orgname.crm.dynamics.com;AuthType=OAuth;Username=;Password=;AppId=;RedirectUri=;LoginPrompt=Never

Build Task Version:
12.* (preview)
9.* (preview)

Task Name: Import Solutions Using Config (Preview)

**Comment by SnehaSoma** [comment]
This issue is now resolved. We realized that the issue is not with build task but with the password.

**Comment by WaelHamze** [comment]
@SnehaSoma thanks for the update. Glad it is working.
