### ISSUE TITLE
Connection String - Token Based Auth.?

### ISSUE THREAD

**Issue by stephenacrown** [WaelHamze/dyn365-ce-vsts-tasks#21]
Hi @WaelHamze 

I've had a look through existing issues but cannot find something that matches what we're looking for assistance/advice with.

Main ask: how can we stop using a username/password combo (in connection string) for creating/deleting environments, and importing solutions and data, and move to token based auth.? Is this something on your radar?

### Context/Detail:

We're using MS Graph API for programmatically consuming/writing to services that are fronted by the MS Graph API (AzureAD, InTune, O365 etc.) - and for now at least - Dynamics 365 CE is not part of the Graph API abstraction capability.

On our Azure DevOps pipelines (_apart from Dynamics 365 where we use a Global Admin user account in Connection String format and therefore basic/legacy auth._) we use Token Based auth. to get access to  services and associated configurations to carry out CRUD operations as part of Infrastructure and Configuration as code. This works well, and is secure and not vulnerable to basic/legacy auth. attacks.

We need to move away from using a Global Admin account for Dynamics 365 deployments (Azure DevOPs pipelines) as MFA cannot currently be enabled (as the deployment tasks fail for obvious reasons), therefore posing a security risk compared to modern auth (token based auth).

I've taken a look at the documentation, but as per this URL, it seems as though Dynamics 365 is quite a way behind other MS services as far as auth. goes. Is this a fair point?

https://docs.microsoft.com/en-us/dynamics365/customer-engagement/developer/xrm-tooling/use-connection-strings-xrm-tooling-connect

Is there anything we're missing here, or any workarounds you're aware of?

Thank you

Stephen

FYI - we've used the following as handy guide for getting token auth. working for Graph API.

http://codematters.tech/getting-access-token-for-microsoft-graph-using-oauth-rest-api/

**Comment by WaelHamze** [comment]
@stephenacrown 

You don't need a Global Admin to manage Dynamics. You can have dedicated accounts per environment/boundary and give them Dynamics 365 Admin: https://docs.microsoft.com/en-us/dynamics365/customer-engagement/admin/use-service-admin-role-manage-tenant

For production you could consider using privilege access management. (e.g. lock the accounts outside of deployment window, expire password so they are required to be set during deployment, further restrictions etc...)

https://docs.microsoft.com/en-us/azure/active-directory/privileged-identity-management/pim-configure
https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/overview

Were you successful in using OAuth by the way in the connection string?

**Comment by stephenacrown** [comment]
Hi @WaelHamze 

Really, thank you for this. Looks like you're right as per the link you sent, so we'll test this out (downgrading the deployment account from Global Admin to Dy365 _**Service**_ Admin)

There looks to have been two elements that had led me to the previous understanding:

1. MS Documentation (that I think needs to be updated) relating to provisioning/deleting instances through the GUI which state a pre-req of Global Admin (that I assumed would be accurate and be no different to SDK based deployment) - note all of these pages state Global Admin needed:

https://docs.microsoft.com/en-us/dynamics365/customer-engagement/admin/manage-online-instances
https://docs.microsoft.com/en-us/dynamics365/customer-engagement/admin/add-instance-subscription
https://docs.microsoft.com/en-us/dynamics365/customer-engagement/admin/delete-instance
https://docs.microsoft.com/en-us/dynamics365/customer-engagement/admin/manage-sandbox-instances



1. Confusing "Dynamics 365 **_System_** Admin" (that's within an instance/env. only) and "Dynamics 365 **_Service_** Admin" - which of course is what I was after for carrying out provisioning/deletion/backup tasks etc. Being new to Dynamics, and dealing more with the pipeline/promote to production side of things rather than within Dynamics itself, I'd not appreciated the difference given at a glance the name looks and sounds so similar.

Re: OAuth, we've been trying to get (and succeeding with basic tests) API calls (authenticated via tokens) working using Postman (see link below). But translating that into something we can use for deployments via the SDK/powershell is the next challenge (importing solutions, data via API?), and the connection string for PackageDeployer doesn't seem (on the face of it) cut out for modern/token based auth. That said, I'm reaching out to see if you/anyone else has moved away from "service accounts" using basic auth., as it is likely I'm missing something!

https://docs.microsoft.com/en-us/dynamics365/customer-engagement/developer/webapi/use-postman-perform-operations

**Comment by stephenacrown** [comment]
I've logged the feedback as GitHub Issues (#534 to #537 over on: https://github.com/MicrosoftDocs/dynamics-365-customer-engagement) for those pages that give Global Admin incorrectly as the role to use rather then Dyn 365 Service Admin.

**Comment by stephenacrown** [comment]
The above pages have been uplifted to state Global Admin is not required, and that Dynamics 365 Service Admin is the preferred role for the type of tasks that this repo/SDK deals with.

@WaelHamze 

I have been pushing Microsoft for when modern/token auth. will be available for Dynamics 365 CE SDK, and yesterday received the following positive news that indicates it might not be too long:

> I was advised that the Dynamics SDK would have to have ADAL implemented to support modern authentication. In a similar SR I have, I was advised that implementing ADAL to Dynamics might take a couple of months or so. This is the most current information I have on this. This may be due to change, and the time of the ETA may vary depending on the challenges the relevant team faces during the process.


Hope this is useful. I'll keep this issue updated with any further info I get.

**Comment by stephenacrown** [comment]
The latest I have on this is that there is still no ETA I’m afraid.

**Comment by WaelHamze** [comment]
You can use clientsecret auth in most of the tasks now

https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/xrm-tooling/use-connection-strings-xrm-tooling-connect
