### ISSUE TITLE
Updating MSCRM Tasks to Latest Versions

### ISSUE THREAD

**Issue by AlexSpodkiewicz** [WaelHamze/dyn365-ce-vsts-tasks#212]
Hi all,

Hopefully a quick question all the various tasks I use are currently V9 is there any issues updating to latest versions just by changing the version to 12 that I need to be aware of?

Thanks

Alex

**Comment by WaelHamze** [comment]
@AlexSpodkiewicz you will need to change all the tasks for v12 in one go and specifically the tool installer as well. These will use the latest version of the SDK and Tools (i.e. solution packager, package deployer etc...). Things should work but always a good practice to test and check if everything is working still as expected.

**Comment by AlexSpodkiewicz** [comment]
@WaelHamze Thanks for getting back to me will give it a go.
