### ISSUE TITLE
Get solution details (preview) does not set variables defined in task

### ISSUE THREAD

**Issue by bananamufu** [WaelHamze/dyn365-ce-vsts-tasks#216]
Hi,

this might just be due to my own incompetence or the preview status of the task, but although the task correctly prints out the solution details in the console, it does not seem to set the assigned pipeline variables to their values.

![image](https://user-images.githubusercontent.com/31623883/96144465-7c9ecd80-0f04-11eb-83fc-917fca400d55.png)

![image](https://user-images.githubusercontent.com/31623883/96141349-36943a80-0f01-11eb-824c-2fa1abf6b6e4.png)

Next action (powershell):

    Write-Host "exists: " $env:EXISTS
    Write-Host "displayname: " $env:DISPLAYNAME
    Write-Host "version: " $env:VERSION

Outputs:

![image](https://user-images.githubusercontent.com/31623883/96144668-b4a61080-0f04-11eb-938c-dac6069317ab.png)

Kind regards,
Tom

**Comment by WaelHamze** [comment]
@bananamufu for this task you need to define the variable in your pipeline first and then put the variables name without the $(). So instead of $(exists) just put exists

**Comment by bananamufu** [comment]
Hey @WaelHamze,

I thought I had tried it that way as well, but apparently that wasn't the case. It seems to be working now! Thanks a lot.

Kind regards,
Tom

**Comment by Sonali79-FS** [comment]
Hello @bananamufu I am having the same issue with saving the values in the pipeline variables. Any suggestions?

**Comment by sstridsberg** [comment]
> Hello @bananamufu I am having the same issue with saving the values in the pipeline variables. Any suggestions?

You need to just input the variable name, not call the variable value: "variablename" instead of "$(variablename)"
