### ISSUE TITLE
Plugin registration fails when assembly contains "Associate" step

### ISSUE THREAD

**Issue by michsob** [WaelHamze/dyn365-ce-vsts-tasks#22]
Hi,

I use Get-XrmPluginRegistration to generate JSON with plugin  definitions.
Step for Associate plugin looks as follows:
{
      "Id": "c8174b36-a391-42e8-a1e4-0854fc15d200",
      "Description": null,
      "Name": "xxx",
      "FriendlyName": "4e54d6f4-4742-4358-23d3-499d39f7bd42",
      "TypeName": "xxx",
      "Steps": [
        {
          "Id": "516934fd-2ad7-e611-80df-005056b355bf",
          "Name": "xxx: Associate of any Entity",
          "MessageName": "None",
          "Description": "xxx: Associate of any Entity",
          "CustomConfiguration": null,
          "FilteringAttributes": null,
          "ImpersonatingUserFullname": "",
          "Mode": "Synchronous",
          "PrimaryEntityName": "none",
          "Rank": 1,
          "Stage": "Postoperation",
          "SupportedDeployment": "ServerOnly",
          "Images": []
        }
      ],
      "WorkflowActivityGroupName": null
    }

When later on I try to deploy DLL using generated JSON with Set-XrmPluginRegistration I get following error:
sdkmessage With Id = 00000000-0000-0000-0000-000000000000 Does Not Exist

The same problem happens for Assign and CalculatePrice message. I suspect this relates to MessageName being set as None instead of correct message name

**Comment by WaelHamze** [comment]
@michsob are you still having this issue? the message name "None" is generating by the Get-XrmPluginRegistration?

**Comment by michsob** [comment]
@WaelHamze In addition to above issues Set-XrmPluginRegistration fails to register plugin on action.
JSON generated from Get-XrmPluginRegistration:
{
      "Id": "c1f0cc72-f0e5-4457-882f-e366835406af",
      "Description": null,
      "Name": "xxxname",
      "FriendlyName": "f2886ddc-59d6-4a18-ba4f-5788d0cb5f31",
      "TypeName": "xxxtypename",
      "Steps": [
        {
          "Id": "905b43aa-5afc-e811-a985-0022480050c6",
          "Name": "POSTExecutionAction of xxx",
          "MessageName": "CustomOperation",
          "Description": "POSTExecutionAction of xxx",
          "CustomConfiguration": null,
          "FilteringAttributes": null,
          "ImpersonatingUserFullname": "",
          "Mode": "Synchronous",
          "PrimaryEntityName": "xxx",
          "Rank": 1,
          "Stage": "Postoperation",
          "SupportedDeployment": "ServerOnly",
          "Images": []
        }
      ],
      "WorkflowActivityGroupName": null
    }

**Comment by WaelHamze** [comment]
I suggest you re-generate your json using latest version https://www.nuget.org/packages/XrmCIFramework/9.0.0.31

and use v 11 of the Plugin Registration Task
