### ISSUE TITLE
Export solution failed with error

### ISSUE THREAD

**Issue by HIREN-AITC** [WaelHamze/dyn365-ce-vsts-tasks#220]
I have created new CRM instance and trying to export solution from that. but it failed with below error.

##[warning]Invalid Login Information : An unsecured or incorrectly secured fault was received from the other party. See the inner FaultException for the fault code and detail.
An unsecured or incorrectly secured fault was received from the other party. See the inner FaultException for the fault code and detail. => Authentication FailureUnable to Login to Dynamics CRM

I use same authentication to login to CRM and it works but doesn't work from task.

AuthType=Office365;Username=$(DeploymentUserName);Url=$(CRMUrl);Password=$(DeploymentUserPassword);RequireNewInstance=true;

**Comment by WaelHamze** [comment]
@HIREN-AITC do you have MFA enabled?

Do you use hosted or private agents?

**Comment by HIREN-AITC** [comment]
Hi @WaelHamze The problem is resolved, it was dues to MS has disabled WS-Auth in new instances and the problem occurred does to that. So I had to add additional parameters in our connection string and then it started working. Thanks for the help.
