### ISSUE TITLE
Set version task throwing invalid format error

### ISSUE THREAD

**Issue by mrsdotnet** [WaelHamze/dyn365-ce-vsts-tasks#231]
I am setting the Version as 1.2.0$(Rev:.r) expecting this will increment the revision number by 1 for CRM solution.
However I get the below error on running the build pipeline:
The version is in an invalid format. Version: 1.2.0$(Rev:.r)

Is this the correct way of using?

**Comment by mattp65** [comment]
That format works in the Options for the pipeline itself, but not in 1 of the steps. There are varaiable available to get the generated Build Number to pass into the action, but the action expects a properly formatted Build ID to be passed in. Personally, I extract the value with a PowerShell action from the BUILD_BUILDNUMBER env variable.

**Comment by WaelHamze** [comment]
@mattp65 thanks
