### ISSUE TITLE
Migrating Configuration data 

### ISSUE THREAD

**Issue by wunnavabk** [WaelHamze/dyn365-ce-vsts-tasks#24]
Is there a way we can migrate Configuration data, as we have Dynamics Portals we want to migrate the configuration data from one env to other during CICD build process

Kindly Advise

**Comment by stephenacrown** [comment]
HI  @wunnavabk 

Please see here in case this already answers your question:

https://github.com/WaelHamze/xrm-ci-framework/issues/170#issuecomment-442172318
