### ISSUE TITLE
Unable to Login to Dynamics CRM using Authtype=Office365

### ISSUE THREAD

**Issue by Gawandevaishnavii** [WaelHamze/dyn365-ce-vsts-tasks#247]
AuthType=Office365;Url=https://orgname.crm7.dynamics.com;Username=userid;Password=password

While using **AuthType=OAuth;Url=https://orgname.crm7.dynamics.com;Username=userid;Password=Password;AppId=726a46fb-55c6-4ad1-add8-xxxxxxxxxx;RedirectUri=https://org.com;client_secret=b3ecb3bf-305b-4a19-xxxx-xxxxxxxxxx;LoginPrompt=Never;** also I am unable to login Dynamics CRM.

**Comment by RobNightingale-LSL** [comment]
Hi @Gawandevaishnavii 
This connection method is deprecated and wont work in brand new environments. This will be phased out to exsiting environments as well. 

> This AuthType is deprecated and we recommend to use OAuth as the preferred authentication type. More information: Authenticate using Office365

https://docs.microsoft.com/en-us/powerapps/developer/data-platform/xrm-tooling/use-connection-strings-xrm-tooling-connect

You should switch to AuthType=OAuth and make note of the "note" box here: https://docs.microsoft.com/en-us/powerapps/developer/data-platform/xrm-tooling/use-connection-strings-xrm-tooling-connect#connection-string-parameters

**Comment by herr-mueller** [comment]
Hi @Gawandevaishnavii,

additional to @RobNightingale-LSL remarks, try to change the version of the build task to a newer one, if its on an old version.

![image](https://user-images.githubusercontent.com/16501728/121639697-34cd4780-ca8d-11eb-97c7-53663bea6512.png)

**Comment by Gawandevaishnavii** [comment]
@RobNightingale-LSL 

Thank you for your assistance.

Its working fine now..

**Comment by WaelHamze** [comment]
@RobNightingale-LSL thank you
