### ISSUE TITLE
Extension is currently flagged as "Preview"  What is the timeline for GA?

### ISSUE THREAD

**Issue by t-anderson** [WaelHamze/dyn365-ce-vsts-tasks#252]
Hello: My Azure DevOps users are interested in this extension. I see the extension is currently flagged as "Preview". What is the timeline for GA? Thank you!

**Comment by WaelHamze** [comment]
@t-anderson the extension status as change to public. Some tasks especially new ones may remain in preview. Please check the license for for details: https://github.com/WaelHamze/dyn365-ce-vsts-tasks/blob/master/LICENSE.txt
