### ISSUE TITLE
List all solutions?

### ISSUE THREAD

**Issue by ephenix** [WaelHamze/dyn365-ce-vsts-tasks#26]
Is there a way to list all managed/unmanaged solutions from a crm environment using this toolkit?

**Comment by WaelHamze** [comment]
@ephenix there is no VSTS task for this at the moment.

Using the PowerShell Cmdlets you can run a fetchXML query that can return all solutions including any filters.

https://github.com/WaelHamze/xrm-ci-framework/blob/master/MSDYNV9/Xrm.Framework.CI/Xrm.Framework.CI.PowerShell.Cmdlets/GetXrmEntitiesCommand.cs

What is the use case/scenario here?

**Comment by WaelHamze** [comment]
@ephenix please re-open if you have any further question or details on the scenario you are facing
