### ISSUE TITLE
New Solution Task

### ISSUE THREAD

**Issue by ephenix** [WaelHamze/dyn365-ce-vsts-tasks#27]
Could a task be created to create a new (empty) unmanaged solution?

We're creating an aggregate solution for packaging by copying the components from multiple simple solutions into one prior to export. ideally, we would like to create the target solution on the fly.

Is this possible?

**Comment by WaelHamze** [comment]
@ephenix Yes great idea I will add it to the backlog

**Comment by WaelHamze** [comment]
Released to Marketplace
