### ISSUE TITLE
Problems with Plugin Steps getting disabled on deployment

### ISSUE THREAD

**Issue by sarria88** [WaelHamze/dyn365-ce-vsts-tasks#28]
Hi all

We have an issue when using the Tools. Everything works fine except when we deploy Plugin Steps . Once the solution is imported into the Target CRM all SDK Message Processing Steps are disabled.

Does anyone found a workaround for this issue?

Cheers,

Miguel

**Comment by sarria88** [comment]
Found a solution.

Basically we need to tick the option "Publish Workflows" on the MSCRM Import Solution step.

![image](https://user-images.githubusercontent.com/22100081/49457684-29757300-f7e3-11e8-8642-6452ace8b891.png)

**Comment by WaelHamze** [comment]
@sarria88 Yes that is the correct way to resolve assuming you want everything activated :)
