### ISSUE TITLE
Activate Flows Advanced Activate does not work

### ISSUE THREAD

**Issue by medicineshow** [WaelHamze/dyn365-ce-vsts-tasks#284]
In the task Activate Flows, the advanced activate type only activated a single flow. The first one in the JSON file.
The JSON file used was:
{
  "Flows": [
    {
      "FlowName": "Child",
      "ShareWith": [
        {
          "PrincipalType": "User",
          "Principal": "**USER UPN WAS HERE**",
          "RoleName": "Owner"
        }
      ],
      "State":  "On"
    },
    {
      "FlowName": "Parent",
      "ShareWith": [
        {
          "PrincipalType": "User",
          "Principal": "**USER UPN WAS HERE**",
          "RoleName": "Owner"
        }
      ],
      "State": "On"
    }
  ]
}

**Comment by medicineshow** [comment]
[tasklog_13.log](https://github.com/WaelHamze/dyn365-ce-vsts-tasks/files/11199092/tasklog_13.log)

There were no errors. I have removed identifying info from the log.

**Comment by Bipuljain04** [comment]
when we use Activate Flow (Preview) in that there 2 options Basic and Advanced - 
1. Basic is working we just provide the files name it working.
2. But for multiple files we need to use in Advanced in that we have to create the JSON file and fetch that. but that was not working and no error. 

![ActiveFlow](https://github.com/WaelHamze/dyn365-ce-vsts-tasks/assets/131649921/aa15a2e3-5e05-4e76-b521-c8b4e40aea74)

**Comment by Bipuljain04** [comment]
{
  "Flows": [
    {
      "FlowName": "Update POD SharePoint Metadata",
      "State":  "Off"
    },
    {
      "FlowName": "Update Signed Document Properties",
      "State": "Off"
    }
  ]
}

**Comment by Bipuljain04** [comment]
@WaelHamze how much time required to fix this - help wanted.

**Comment by tvking** [comment]
@Bipuljain04  @medicineshow  I've created a PR that should fix this issue https://github.com/WaelHamze/dyn365-ce-vsts-tasks/pull/306 @WaelHamze are you able to have a look at this please? My team are also blocked in using the activateFlows task.
