### ISSUE TITLE
Connect String for Dynamics 365

### ISSUE THREAD

**Issue by ptownsen** [WaelHamze/dyn365-ce-vsts-tasks#3]
Hi Wael,

I am trying to use your CRM Build Tools within Azure DevOps but I am having issues with the authentication between the various MSCRM tasks and my Dynamics 365 trial instance.  We authenticate to Dynamics online using ADFS on-premise.  I have tried using various connect strings in the build tasks but to  no avail.  The CRM Connection Strings I have tried are:

**AuthType=IFD;Username=$(CrmUsername); Password=$(CrmPassword); Url=https://litens0.crm4.dynamics.com** 

This connect string results in:
**Couldn't connect to CRM instance after 3 attempts: Unable to Login to Dynamics CRM**

If try using AuthType=OAuth instead of IFD, I get the following error message from MSCRM task:
**ClientId or Redirect uri cannot be null or empty.
Parameter name: ClientId and Redirect Name**

Should I be using OAuth for this configuration?  If so what is the Client ID it is expecting, the VSTS build server?  Not sure if you have encountered this kind of configuration before but any suggestions would be greatly appreciated.

Peter Townsend

**Comment by WaelHamze** [comment]
Hi Peter,

Thanks for reaching out. Please take a look at this issue for suggestions: https://github.com/WaelHamze/xrm-ci-framework/issues/150

Regarding clientId, Here is some information on ClientId: https://docs.microsoft.com/en-us/dynamics365/customer-engagement/developer/walkthrough-register-dynamics-365-app-azure-active-directory

Hope this helps. Once you get the Ping task working hopefully the rest will be a lot easier.
