### ISSUE TITLE
PublishCustomization tasks run into timeout

### ISSUE THREAD

**Issue by herr-mueller** [WaelHamze/dyn365-ce-vsts-tasks#30]
Hi Wael,

we are using your tasks on our VSTS for automated deployment. After upgrading our instances to v9.1 the builds don't run successfully anymore: The PublishCustomizations tasks runs into timeout after an hour or so without any error. If I do Publish All on the web client, everything works fine after some moments.

![image](https://user-images.githubusercontent.com/16501728/49638990-185a7b00-fa0a-11e8-8c6d-8de7341ecd55.png)

Do you have any experience with this issue and any advice, how we could resolve this?

Cheers,
Joe

**Comment by WaelHamze** [comment]
@herr-mueller there is not much I can do in the code about this. I have noticed in some situations that certain operations work in UI and not through SDK like solution import in some cases. I suggest you raise a case with MS so they can investigate if you have a consistent repro.

**Comment by davegoopot** [comment]
@herr-mueller and @WaelHamze we are tripping over a similar sounding problem running the Azure DevOps pipeline command MSCRMApplySolution@10. Did either of you ever find out  how we might avoid the issue?

I'm happy to pick this up and raise with MS support (we have a prem support subscription). I might need some help figuring out how to get this in a format MS will use.
