### ISSUE TITLE
Issue with MSCRMApplySolution

### ISSUE THREAD

**Issue by ikshavakulathula** [WaelHamze/dyn365-ce-vsts-tasks#307]
Dear @WaelHamze , Thank you for your efforts. I'm using your Azure DevOps Task for the CRM Import and Export however, I'm facing issues.

The concern here is import solution is success, and the solution upgrade is also success, but we don't see the solution getting upgraded in the CRM server

- task: MSCRMImportSolution@12
            inputs:
              crmConnectionString: '$(import_QDBXCatalog_uat)'
              solutionFile: '$(Build.ArtifactStagingDirectory)/TestXCatalog/${{ parameters.Sol_name }}_managed_$(Build.BuildId).zip'
              publishWorkflows: true
              overwriteUnmanagedCustomizations: true
              override: true
 - task: MSCRMApplySolution@12
             inputs:
               crmConnectionString: '$(import_QDBXCatalog_uat)'
               solutionName: '$(Build.ArtifactStagingDirectory)/TestXCatalog/${{ parameters.Sol_name }}_managed_$(Build.BuildId).zip'

**Comment by ikshavakulathula** [comment]
Output for the apply solution upgrade.

![image](https://github.com/user-attachments/assets/79ccea2f-857d-4b5e-9b2e-475ee2a8dd21)

**Comment by mattp65** [comment]
Check the log you attached.  Looks like you are passing the Zip file name, not the solution name when calling the action.

**Comment by ikshavakulathula** [comment]
Dear @mattp65 , I think that is ok.
If there is an issue with extension (.zip) it should not even import. Here the import is success and **issue is with upgrade**

Note: Our pipeline will do the following tasks.

It will export from Dev environment, upload the exported solution in Jfrog and during import stage, we will download from Jfrog and import it in the uat environment, as mentioned the import is ok **but the issue is with upgrade**

Sharing the worked scenario for other pipeline with import task and output of it

 - task: MSCRMImportSolution@12
            inputs:
              crmConnectionString: $(import_XXXXX_uat)
              solutionFile: '$(Build.ArtifactStagingDirectory)/CRM-XXXXX/${{ parameters.Sol_name }}_$(Build.BuildId).zip'
 
Output: 
    
Importing Solution: C:\azureworkspace\13\a\CRM-XXXX\XXXXSChangeV2_29501.zip
Solution Zip Size: 2.35 KB
Solution Unique Name: XXXSChangeV2, Version: 1.0.0.0
XXXSChangeV2 not currently installed.
Async Operation completed with status: Succeeded
Async Operation completed with message: 
Completed Progress: 100
Completed On: 8/19/2024 3:17:06 PM
Import Result: success
Import Error: 
Total number of unprocessed components: 0
Import Job Log successfully saved to: C:\azureworkspace\13\s\ImportLog_XXXXChangeV2_295012024_08_19__18_16.xml
Solution Import Completed Successfully

**Comment by ikshavakulathula** [comment]
Dear @WaelHamze ,

Tested the pipeline again

In the below screenshot, the newer version of same solution is getting imported but it is not deleting the older version of the same solution. kindly suggest me if I'm missing something here. Thank you in advance

![image](https://github.com/user-attachments/assets/bd916b73-daab-4bd4-9ec4-47515247f308)

**Comment by ikshavakulathula** [comment]
Dear @WaelHamze , @mattp65 , , can you assist me here

**Comment by parvezghumra** [comment]
@ikshavakulathula As @mattp65 mentioned, in the "Apply Solution" you need to pass the solution unique name (without _Upgrade suffix) not the solution zip file name

**Comment by ikshavakulathula** [comment]
@parvezghumra , Yeah you are right, I fixed the pipeline issue, now it is working as expected. Thank you
