### ISSUE TITLE
The element 'forms' has invalid child element 'forms'. List of possible elements expected: 'systemform'.'. 

### ISSUE THREAD

**Issue by bwilliam45** [WaelHamze/dyn365-ce-vsts-tasks#31]
Used spkl unpack to contact Dyn365 8.2 instance, get everything, bring it locally.
Then used MSCRM Pack Solution in tfs on-prem build, and then Deploy Dynamics 365 Package and Data using Package Deployer to deploy it back out to same Dyn365 8.2 instance.
Get error:   
The element 'forms' has invalid child element 'forms'. List of possible elements expected: 'systemform'.'. The validation failed at: '...

with a Entities entity FormXML guid.xml file...

**Comment by WaelHamze** [comment]
@bwilliam45 what version of task you are using?

I suggest you try to run this package locally using powershell interface and see what happens.

**Comment by WaelHamze** [comment]
Closing as there is no action I can take on this.
