### ISSUE TITLE
Enhancement: Publish few entities at once When Publish All Fails

### ISSUE THREAD

**Issue by carolina007** [WaelHamze/dyn365-ce-vsts-tasks#32]
Enhancement: 
When we publish the entire solution, sometimes we get a generic SQL error.  Could you add a feature to publish few entities at once. Currently we are using sdk to call RetrieveAllEntitiesRequest and publishing few entities at once and it's working fine.

public void PublishInChuncks(string server, string param_ORGName, int param_iTotalEntitiesToPublish)
{
    int iCount = 0;
    int iCountStatus = 0;
    int iTotalEntityCount = 0;
    PublishXmlRequest pubRequest = new PublishXmlRequest();
    PublishXmlResponse publishResponse = new PublishXmlResponse();

    RetrieveAllEntitiesRequest objRetrieveAllEntityRequest = new RetrieveAllEntitiesRequest();
    RetrieveAllEntitiesResponse objRetrieveAllEntityResponse = new RetrieveAllEntitiesResponse();

    StringBuilder sbImportXML = new StringBuilder("<importexportxml><entities>");

    // Retrieve the MetaData.
    objRetrieveAllEntityRequest.RetrieveAsIfPublished = true; // Set this value to true to include unpublished changes, as it would look if you called publish
    objRetrieveAllEntityRequest.EntityFilters = EntityFilters.Entity;
    objRetrieveAllEntityResponse = _proxy.Execute(objRetrieveAllEntityRequest);

    iTotalEntityCount = objRetrieveAllEntityResponse.EntityMetadata.Count - 1;

    for (int index = 0; index <= iTotalEntityCount; index++)
    {
        if (objRetrieveAllEntityResponse.EntityMetadata(index).IsCustomizable.Value == true)
            sbImportXML.Append("<entity>" + objRetrieveAllEntityResponse.EntityMetadata(index).LogicalName + "</entity>" + Environment.NewLine);

        if ((iCount == param_iTotalEntitiesToPublish))
        {
            sbImportXML.Append("</entities></importexportxml>");
            // Create new Publish Request
            pubRequest = new PublishXmlRequest();
            pubRequest.ParameterXml = sbImportXML.ToString();
            publishResponse = _proxy.Execute(pubRequest);
            iCountStatus = iCountStatus + iCount;
            ReportStatus?.Invoke("Published " + iCountStatus + " out of " + iTotalEntityCount + " Entities");
            iCount = 0;
            sbImportXML = new StringBuilder("<importexportxml><entities>");
        }

        iCount = iCount + 1;
    }

    _proxy.Dispose();
    return AccessResult.Success;
}

**Comment by carolina007** [comment]
Timeout is from MS backend. We have tried increasing the OLEDBTimout etc. This happens when we have large number of field level security entities. We didn't report this to Microsoft yet.

**Comment by WaelHamze** [comment]
@carolina007 I suggest you pass this by MS first, I am trying to keep this task generic and in most cases users will need to publish more components that just entities.

**Comment by carolina007** [comment]
Sure, Please close this.
