### ISSUE TITLE
[error]Invalid number of components in version.

### ISSUE THREAD

**Issue by greenrya** [WaelHamze/dyn365-ce-vsts-tasks#36]
I have built a Azure Devops Pipeline build that uses the MSCRM Export Solution task.  It is failing with a invalid number of components in version.  I tried with an existing solution and a new solution in my CRM enviornment.  Something I have configured wrong?  Our D365 CRM version is Version 1710 (9.1.0.1117) online Thanks!

**Comment by WaelHamze** [comment]
Did you tick the update version? If so then you need to make sure the build number matches this format:

[name]_[version] e.g. CRMBuild_1.0.0.2

**Comment by greenrya** [comment]
Thanks!

On Tue, Jan 8, 2019 at 2:10 PM WaelHamze <notifications@github.com<mailto:notifications@github.com>> wrote:

Did you tick the update version? If so then you need to make sure the build number matches this format:

[name]_[version] e.g. CRMBuild_1.0.0.2

**Comment by greenrya** [comment]
Sorry I really can not get version to update tried many different combinations is there a help link on this setting?

**Comment by greenrya** [comment]
One additional question I would like to check-in the exported solution to Azure DevOps is there a build task for this?

**Comment by greenrya** [comment]
For the build number I believe I have found the setting try now.

**Comment by WaelHamze** [comment]
@greenrya you can also untick this option and use the set version task.

Regarding check-in to VSTS, I don't have a task to do this. I suggest you publish this as an artifact.

**Comment by mattp65** [comment]
In order for the task to “extract” the build number, the build has to be the last part of the value. I have found that it is easier to explicitly determine this elsewhere and then pass in just the desired value. As for Check-In, I have used “TFVC Build Tasks” extension for this capability.

**Comment by greenrya** [comment]
Sounds great got it working on that.  This is a very simple principal and my last task is to check in the exported solution so we can compare version working on that next chime in if you have ideas.  Such a great tool!

**Comment by WaelHamze** [comment]
@greenrya glad you got this working. I suggest to take a look at this issue for your other requirement. https://github.com/WaelHamze/xrm-ci-framework/issues/95
