### ISSUE TITLE
Tasks not working, but Cmdlets do

### ISSUE THREAD

**Issue by PilotC150** [WaelHamze/dyn365-ce-vsts-tasks#39]
I'm trying to automate the deployment of some files and then want to export the resulting solution (both managed and unmanaged).  I'm running into problems.  This is being done on a Dynamics 365 instance.

The two tasks that I'm running are (obviously) Update Web Resources and Export Solution.

I have the appropriate json mapping file built and checked into my repository and it is formatted correctly.  When I run my build everything appears to be working correctly.  All of the logs say it's working, but I'm seeing strange behavior.

When I look at the web resource files, the files haven't changed.  Also, on the Export Solution task I have it set to update the solution version.  Again, the logs appear to show it's working but the solution version never changed.

Here's where it gets strange:  When I take the exported unmanaged solution zip file and open it up, my file changes are in there.  How?

The next strange part: When I run the cmdlets directly from powershell (Set-XrmWebResource and Set-XrmSolutionVersion) then everything works.  Files are updated and/or solution version is changed.  The output from those looks identical to the output from the build tasks in Azure Devops.

I don't understand why it's working in one context but not in another.

Can anybody help?

**Comment by PilotC150** [comment]
This was caused by my own typo that was causing me to deploy to one Dynamics instance but test for the changes on a different instance.

**Comment by WaelHamze** [comment]
Glad you got this fixed 👍
