### ISSUE TITLE
Beginner's guide & Crm Permission Error

### ISSUE THREAD

**Issue by rexkenley** [WaelHamze/dyn365-ce-vsts-tasks#4]
Hi

Is there a beginner's guide that I can refer to?  Also I am having issues importing a solution using the MSCRM Import Solution,

"You do not have the necessary permissions to change the domain logon name for this user."

Unhandled Exception: System.ServiceModel.FaultException`1[[Microsoft.Xrm.Sdk.OrganizationServiceFault, Microsoft.Xrm.Sdk, Version=8.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]: Access is denied.Detail: 
<OrganizationServiceFault xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.microsoft.com/xrm/2011/Contracts">
  <ActivityId>7d3c5cbd-b0ff-46be-bc47-610798da7692</ActivityId>
  <ErrorCode>-2147187707</ErrorCode>
  <ErrorDetails xmlns:d2p1="http://schemas.datacontract.org/2004/07/System.Collections.Generic" />
  <Message>Access is denied.</Message>
  <Timestamp>2018-09-21T19:29:39.572389Z</Timestamp>
  <ExceptionSource i:nil="true" />
  <InnerFault>
    <ActivityId>7d3c5cbd-b0ff-46be-bc47-610798da7692</ActivityId>
    <ErrorCode>-2147187707</ErrorCode>
    <ErrorDetails xmlns:d3p1="http://schemas.datacontract.org/2004/07/System.Collections.Generic" />
    <Message>Access is denied.</Message>
    <Timestamp>2018-09-21T19:29:39.572389Z</Timestamp>
    <ExceptionSource i:nil="true" />
    <InnerFault>
      <ActivityId>7d3c5cbd-b0ff-46be-bc47-610798da7692</ActivityId>
      <ErrorCode>-2147220970</ErrorCode>
      <ErrorDetails xmlns:d4p1="http://schemas.datacontract.org/2004/07/System.Collections.Generic" />
      <Message>System.UnauthorizedAccessException: Microsoft Dynamics CRM has experienced an error. Reference number for administrators or support: #9903ACB6</Message>
      <Timestamp>2018-09-21T19:29:39.572389Z</Timestamp>
      <ExceptionSource i:nil="true" />
      <InnerFault i:nil="true" />
      <OriginalException i:nil="true" />
      <TraceText i:nil="true" />
    </InnerFault>
    <OriginalException i:nil="true" />
    <TraceText i:nil="true" />
  </InnerFault>
  <OriginalException i:nil="true" />
  <TraceText i:nil="true" />
</OrganizationServiceFault>
   at Microsoft.Crm.Extensibility.OrganizationSdkServiceInternal.Execute(OrganizationRequest request, CorrelationToken correlationToken, CallerOriginToken callerOriginToken, WebServiceType serviceType, Boolean checkAdminMode, ExecutionContext executionContext)
   at Microsoft.Crm.Extensibility.InprocessServiceProxy.ExecuteCore(OrganizationRequest request)
   at Microsoft.Crm.Asynchronous.ExecuteSdkMessageOperation.InternalExecute(AsyncEvent asyncEvent)

Thanks!

**Comment by WaelHamze** [comment]
@rexkenley Are you able to import the same solution using the UI? I presume the user in the connection string has system admin on the target instance?

**Comment by rexkenley** [comment]
Yes, I was. 

The account that I am using is a member of the admin role in Crm. Should I add that account as a local admin as well?
