### ISSUE TITLE
Using Import Log file variable

### ISSUE THREAD

**Issue by carolina007** [WaelHamze/dyn365-ce-vsts-tasks#40]
Tried both adding PowerShell to display the value in $env:SOLUTION_IMPORT_LOG_FILE but it's not working. We are using version 11

Write-Host $env:SOLUTION_IMPORT_LOG_FILE

Write-Host $(SOLUTION_IMPORT_LOG_FILE)

2019-01-17T18:47:47.1537177Z ##[error]SOLUTION_IMPORT_LOG_FILE : The term 'SOLUTION_IMPORT_LOG_FILE' is not recognized as the name of a cmdlet, function, 
script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is 
correct and try again.
At C:\Users\e2tsbD2\AppData\Local\Temp\1fa38ae8-8bd8-4940-83a8-6a463d20730d.ps1:8 char:14
+ Write-Host $(SOLUTION_IMPORT_LOG_FILE)

Could you please help us?

**Comment by WaelHamze** [comment]
@carolina007 you need to use the below

Write-Host $(MSCRMImportSolution1.SOLUTION_IMPORT_LOG_FILE)

Where MSCRMImportSolution1 is the reference show in VSTS Task

![image](https://user-images.githubusercontent.com/11046518/51344905-92fac980-1a91-11e9-8cad-d9d4dfb93acd.png)

**Comment by carolina007** [comment]
Thank you Wael,  We are not seeing Output Variables tab. It's missing in version 11 or prior versions.

Write-Host $(MSCRMImportSolution1.SOLUTION_IMPORT_LOG_FILE)

2019-01-17T20:02:23.6230746Z ##[error]MSCRMImportSolution1.SOLUTION_IMPORT_LOG_FILE : The term 'MSCRMImportSolution1.SOLUTION_IMPORT_LOG_FILE' is not 

2019-01-17T20:00:49.6425532Z ##[error]MSCRMImportSolution.SOLUTION_IMPORT_LOG_FILE : The term 'MSCRMImportSolution.SOLUTION_IMPORT_LOG_FILE' is not

**Comment by carolina007** [comment]
Could you add $logFilename and $logsDirectory property below the connection Timeout? Just like connection property.

**Comment by carolina007** [comment]
Thank you, Yes, Managed solution doesn't generate log files. We are using unmanaged solution.
