### ISSUE TITLE
Solution Versioning

### ISSUE THREAD

**Issue by s-bauer** [WaelHamze/dyn365-ce-vsts-tasks#41]
In the Azure DevOps Build Task "MSCRM Export Solution" it is possible to activate the checkbox "Update Version". This takes the `Build.BuildNumber` and takes everything after the last `_` to update the CRM Solution version.
It would be nice to have the possibility to set the version manually as Task attribute, because it's not always possible to change the Build Number format. In addition when utilizing Azure DevOps Release Definitions it also reads the `Build.BuildNumber` variable instead of the `Release.ReleaseName`!

**Comment by mattp65** [comment]
There is a separate Set Version task that provides more flexibility.

**Comment by s-bauer** [comment]
@mattp65 Yes, I know about that one, but I would prefer to do versioning and export in a singel build step. I've created #42, which adds some more options! Let's see what @WaelHamze has to say about it :)

**Comment by WaelHamze** [comment]
@s-bauer @mattp65 

The ability to update the version as a part of the export is a legacy feature which I will be taking out in future updates.

I think the Set Version task would be the way to do think. I have updated this task to give you the ability to set the version for extracted customizations too.

Ideally I want to avoid duplicate logic to avoid maintenance and confusion.

Unless there is a very strong reason to do this as part of the export, I would advise to use the set version task. This also make it more clear what is going on by looking at the definition.

Let me know your thoughts.

**Comment by s-bauer** [comment]
Alright. I would recommend to add a deprecated label to the step as soon as possible so people move to the other task instead.

**Comment by lheng18** [comment]
@WaelHamze @s-bauer The Set Version Task adds the $BuildNumbers which contains charaters of Build Name. How do we just add the numbers that  after the  _ as CRM version number?
