### ISSUE TITLE
Feature Request: Extract Configuration Migration Tool Data

### ISSUE THREAD

**Issue by berellax** [WaelHamze/dyn365-ce-vsts-tasks#44]
It would be nice to have the ability to automatically extract data using the Configuration Migration tool from a source environment using a pre-defined Export Schema as part of a Build definition, and then be able to use the export in the Package Deployer package in a later step. Further, I would want to unpack/pack the extracted data into TFS similar to the way Solution Packager works.

**Comment by WaelHamze** [comment]
@berellax are you aware of an API that would allow you to extract the data from schema? This is something that MS might offer but at the moment this would mean writing custom code.

**Comment by berellax** [comment]
@WaelHamze I spoke to some folks at Microsoft and the consensus seems to be that while there’s not an API for this now that will be coming soon. I’m trying to gain some clarity on this, and otherwise may pursue a custom tool to export data based on an Export Schema from CMT. Additional features would likely include filter criteria for entities and ability to replace value with environmental variables. I’ll keep you posted.

**Comment by WaelHamze** [comment]
@berellax this is available now in the toolkit
