### ISSUE TITLE
How to update Optionset Field - MSCRM Update Configuration Records

### ISSUE THREAD

**Issue by yohanosullivan** [WaelHamze/dyn365-ce-vsts-tasks#45]
Does anyone know how to update an optionset field using the MSCRM Update Configuration Records?

**Comment by WaelHamze** [comment]
@yohanosullivan the task doesn't support this at the moment, you could consider adjusting and using this script to make it work. https://github.com/WaelHamze/xrm-ci-framework/blob/master/MSDYNV9/Xrm.Framework.CI/Xrm.Framework.CI.PowerShell.Scripts/UpdateConfigurationRecords.ps1

**Comment by WaelHamze** [comment]
This is now possible using environment parameters
