### ISSUE TITLE
How to Pass Simple Optionset (yes/No) Value in to Update Configuration

### ISSUE THREAD

**Issue by subratgaur** [WaelHamze/dyn365-ce-vsts-tasks#46]
We are trying to pass 2 Values to one look up field. 
Example 
LookupField  - Name
Value fields  - Field1, Field2

Field2 is a simple Yes/No optionset.  What is the correct way to represent the 'A json array of lookup/value pairs' and the Yes value of Optionset.

we have tried 

[['TestKey','TestValue3', 'True']]
[['TestKey','TestValue3', 1]]
[['TestKey','TestValue3', '1']]

But all of them error out with "

System.InvalidCastException: Microsoft Dynamics CRM has experienced an error. Reference number for administrators or support: #A36422D1"

What are we doing wrong ?

Any help will be very appreciated.

![image](https://user-images.githubusercontent.com/34252060/52646284-b9006780-2e9f-11e9-9438-4a6794e65389.png)

**Comment by WaelHamze** [comment]
@subratgaur note option sets are not currently supported in this task. This task is only able to set string values for now.

**Comment by WaelHamze** [comment]
This is now possible using environment variables.
