### ISSUE TITLE
Unmanaged Pack Complete - Exit code 5

### ISSUE THREAD

**Issue by crmdruid** [WaelHamze/dyn365-ce-vsts-tasks#49]
Dear Wael,

I wonder if you could point me in the correct direction, I am a little stumped on this one.

Last week friday the 23rd Feb our build was packing the solution correctly, I noticed it was using version 10.0.3 running in a Hosted VS2017 build agent.

Task         : MSCRM Pack Solution
Description  : Packages a CRM Solution using SolutionPackager.exe
Version      : 10.0.3
Author       : Wael Hamze
Help         : Solution files must be checked-in to source control

Today when we ran the build we noticed that the version is 10.0.4

Task         : MSCRM Pack Solution
Description  : Packages a CRM Solution using SolutionPackager.exe
Version      : 10.0.4
Author       : Wael Hamze
Help         : Solution files must be checked-in to source control

What we have setup is to use spkl to unpack the solution and check it into git.

Then with the build tasks you have contributed to the community, we install the mscrm tool and then use the mscrm pack solution DevOps task.

I am receiving an error message today with is stating Exit code 5.

Looked this up and it seems to be access is denied error code, to me it seems like the script is trying to import a module which is running inside the build agent and doesn't have permissions to import modules.

Perhaps I have incorrectly setup the script, any direction for me to look would be appreciated.

`
Unmanaged Pack complete.

##[error]Exit code 5 returned from process: file name 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe', arguments '-NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". ([scriptblock]::Create('if (!$PSHOME) { $null = Get-Item -LiteralPath ''variable:PSHOME'' } else { Import-Module -Name ([System.IO.Path]::Combine($PSHOME, ''Modules\Microsoft.PowerShell.Management\Microsoft.PowerShell.Management.psd1'')) ; Import-Module -Name ([System.IO.Path]::Combine($PSHOME, ''Modules\Microsoft.PowerShell.Utility\Microsoft.PowerShell.Utility.psd1'')) }')) 2>&1 | ForEach-Object { Write-Verbose $_.Exception.Message -Verbose } ; Import-Module -Name 'D:\a\_tasks\MSCRMPackSolution_ebec2a90-ce1f-11e6-ae21-c1fb031659ee\10.0.4\ps_modules\VstsTaskSdk\VstsTaskSdk.psd1' -ArgumentList @{ NonInteractive = $true } -ErrorAction Stop ; $VerbosePreference = 'SilentlyContinue' ; $DebugPreference = 'SilentlyContinue' ; Invoke-VstsTaskScript -ScriptBlock ([scriptblock]::Create('. ''D:\a\_tasks\MSCRMPackSolution_ebec2a90-ce1f-11e6-ae21-c1fb031659ee\10.0.4\MSCRMPackSolution.ps1'''))"'.
##[section]Finishing: MSCRM Pack Solution`

**Comment by bl-pr** [comment]
Hi - We are having similar issue in our builds using the Pack Solution task...

Unmanaged Pack complete.

Packing Solution Completed
##[error]Exit code 6 returned from process: file name 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe', arguments '-NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". ([scriptblock]::Create('if (!$PSHOME) { $null = Get-Item -LiteralPath ''variable:PSHOME'' } else { Import-Module -Name ([System.IO.Path]::Combine($PSHOME, ''Modules\Microsoft.PowerShell.Management\Microsoft.PowerShell.Management.psd1'')) ; Import-Module -Name ([System.IO.Path]::Combine($PSHOME, ''Modules\Microsoft.PowerShell.Utility\Microsoft.PowerShell.Utility.psd1'')) }')) 2>&1 | ForEach-Object { Write-Verbose $_.Exception.Message -Verbose } ; Import-Module -Name 'C:\FSV_agent2\_work\_tasks\MSCRMPackSolution_ebec2a90-ce1f-11e6-ae21-c1fb031659ee\10.0.4\ps_modules\VstsTaskSdk\VstsTaskSdk.psd1' -ArgumentList @{ NonInteractive = $true } -ErrorAction Stop ; $VerbosePreference = 'SilentlyContinue' ; $DebugPreference = 'SilentlyContinue' ; Invoke-VstsTaskScript -ScriptBlock ([scriptblock]::Create('. ''C:\FSV_agent2\_work\_tasks\MSCRMPackSolution_ebec2a90-ce1f-11e6-ae21-c1fb031659ee\10.0.4\MSCRMPackSolution.ps1'''))"'.
##[section]Finishing: MSCRM Pack Solution - unmanaged

**Comment by bl-pr** [comment]
@crmdruid FYI - we have changed the version from 10* to 9* on the task definition and our builds are working again.. We'll use this version until a proper resolution is found...

blpr

**Comment by WaelHamze** [comment]
@crmdruid @bl-pr thanks for highlighting this issue.

There was a release on Saturday that shipped the new version of the task. Now I have tested this on the hosted agent and it worked fine on Saturday.

`##[section]Starting: MSCRM Pack Solution
==============================================================================
Task         : MSCRM Pack Solution
Description  : Packages a CRM Solution using SolutionPackager.exe
Version      : 10.0.4
Author       : Wael Hamze
Help         : Solution files must be checked-in to source control
==============================================================================
Packing Solution from Path: D:\a\1\s\Sample\Xrm.CI.Framework.Sample\Customizations\Solutions\xRMCISample\Customizations
Packing Solution Name: xRMCISample - Version 1.0.0.21
Reading mapping directives...
<FileToFile map="XrmCIFrameworkSamplePlugins.dll" to="..\..\..\..\Xrm.CI.Framework.Sample.Plugins\bin\Release\Xrm.CI.Framework.Sample.Plugins.dll" />
<FileToFile map="XrmCIFrameworkSampleWFActivities.dll" to="..\..\..\..\Xrm.CI.Framework.Sample.WFActivities\bin\Release\Xrm.CI.Framework.Sample.WFActivities.dll" />
<FileToPath map="WebResources\*.*" to="..\..\..\..\Xrm.CI.Framework.Sample.WebResources\WebResources\**" />
<FileToPath map="WebResources\**\*.*" to="..\..\..\..\Xrm.CI.Framework.Sample.WebResources\WebResources\**" />

Packing D:\a\1\s\Sample\Xrm.CI.Framework.Sample\Customizations\Solutions\xRMCISample\Customizations to D:\a\1\a\xRMCISample_managed.zip`

Today this task is working fine, However I am getting this error on another task. But this is strange as it happens after all my scripts finish executing... I wonder if its something to do with PS runtime on the hosted agent.

`Managed Pack complete.

##[debug]SolutionPackager exit code@ 0
1 solutions processed out of 1
Packing Solutions Completed
Packed Solutions to D:\a\1\a
##[debug]Leaving PackSolutionsUsingConfig.ps1
##[debug]Uploading pack log files
##[debug]Uploading pack log D:\a\1\s\PackagerLog_xRMCISample_2019_02_25__06_00.txt
##[debug]Processed: ##vso[task.uploadfile]D:\a\1\s\PackagerLog_xRMCISample_2019_02_25__06_00.txt
##[debug]Pack log uploaded D:\a\1\s\PackagerLog_xRMCISample_2019_02_25__06_00.txt
##[debug]Completed uploading pack log files
##[debug]Leaving MSCRMPackSolutionsUsingConfig.ps1
##[error]Exit code 5 returned from process: file name 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe', arguments '-NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". ([scriptblock]::Create('if (!$PSHOME) { $null = Get-Item -LiteralPath ''variable:PSHOME'' } else { Import-Module -Name ([System.IO.Path]::Combine($PSHOME, ''Modules\Microsoft.PowerShell.Management\Microsoft.PowerShell.Management.psd1'')) ; Import-Module -Name ([System.IO.Path]::Combine($PSHOME, ''Modules\Microsoft.PowerShell.Utility\Microsoft.PowerShell.Utility.psd1'')) }')) 2>&1 | ForEach-Object { Write-Verbose $_.Exception.Message -Verbose } ; Import-Module -Name 'D:\a\_tasks\MSCRMPackSolutionsUsingConfig_33dbb312-a641-4111-8c3e-81f589b41a74\9.0.5\ps_modules\VstsTaskSdk\VstsTaskSdk.psd1' -ArgumentList @{ NonInteractive = $true } -ErrorAction Stop ; $VerbosePreference = 'Continue' ; $DebugPreference = 'Continue' ; Invoke-VstsTaskScript -ScriptBlock ([scriptblock]::Create('. ''D:\a\_tasks\MSCRMPackSolutionsUsingConfig_33dbb312-a641-4111-8c3e-81f589b41a74\9.0.5\MSCRMPackSolutionsUsingConfig.ps1'''))"'.
##[debug]Microsoft.VisualStudio.Services.Agent.Util.ProcessExitCodeException: Exit code 5 returned from process: file name 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe', arguments '-NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". ([scriptblock]::Create('if (!$PSHOME) { $null = Get-Item -LiteralPath ''variable:PSHOME'' } else { Import-Module -Name ([System.IO.Path]::Combine($PSHOME, ''Modules\Microsoft.PowerShell.Management\Microsoft.PowerShell.Management.psd1'')) ; Import-Module -Name ([System.IO.Path]::Combine($PSHOME, ''Modules\Microsoft.PowerShell.Utility\Microsoft.PowerShell.Utility.psd1'')) }')) 2>&1 | ForEach-Object { Write-Verbose $_.Exception.Message -Verbose } ; Import-Module -Name 'D:\a\_tasks\MSCRMPackSolutionsUsingConfig_33dbb312-a641-4111-8c3e-81f589b41a74\9.0.5\ps_modules\VstsTaskSdk\VstsTaskSdk.psd1' -ArgumentList @{ NonInteractive = $true } -ErrorAction Stop ; $VerbosePreference = 'Continue' ; $DebugPreference = 'Continue' ; Invoke-VstsTaskScript -ScriptBlock ([scriptblock]::Create('. ''D:\a\_tasks\MSCRMPackSolutionsUsingConfig_33dbb312-a641-4111-8c3e-81f589b41a74\9.0.5\MSCRMPackSolutionsUsingConfig.ps1'''))"'.
   at Microsoft.VisualStudio.Services.Agent.Util.ProcessInvoker.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, InputQueue`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.ProcessInvokerWrapper.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, InputQueue`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.DefaultStepHost.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Boolean inheritConsoleHandler, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.PowerShell3Handler.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
##[section]Finishing: MSCRM Packs Solutions Using Config
`
I'll continue investigating

**Comment by WaelHamze** [comment]
I ran the build many times and it seems to pass 50% of the time, so seems like intermittent issue. The error seems to occur for after all execution is completed and control is passed back to the VSTS SDK.

Are you able to set "system.debug" to true and share the logs including at what point this error is happening?

**Comment by crmdruid** [comment]
@WaelHamze Thank you for the feedback.

Attached the debug error log now for the MSCRM Pack Solution task, not that much more helpful unfortunately.

[ErrorLog_VS2017Hosted.txt](https://github.com/WaelHamze/dyn365-ce-vsts-tasks/files/2899331/ErrorLog_VS2017Hosted.txt)

The rest of the build pipleline is working, nuget restore, build and unit tests quite odd, not sure if the other logs would be useful as they pretty standard stuff.

Tried it on one other VS2017 hosted agent we have setup and the same results.

What I can do is setup another agent pool tomorrow and get back to you if that made any difference.


@bl-pr Thank you for that, quick question, how were you able to change the version to 9* ? 

I tried from the front end but I only see 10* under version , I also tried exporting the json definition for the pipeline and editing it manually and re-importing, still running 10*.

**Comment by CrmDev23** [comment]
Same issue here. Not sure why this is suddenly popping up.
Currently I'm able to suppress the error by configuring the task as "Continue on error".

**Comment by ziffo777** [comment]
D365 SDK assemblies since version 9.0.2.9 requires .net 4.6.2 or later as a baseline. Could that be an issue?

**Comment by WaelHamze** [comment]
I have just released a hotfix, It might take sometime until this syncs to your account. You should see a new version of the MSCRM Tools Installer (9.0.84). Let me know if this works for you.

**Comment by crmdruid** [comment]
@CrmDev23 thanks but if i set it to continue on error I have the artifact but unable to release a partial build through the pipeline.

@WaelHamze Thank you, I see the new version of the MSCRM Tools Installer.

`Task         : MSCRM Tool Installer
Description  : Installs the Dynamics 365 tools required by all of the tasks
Version      : 9.0.84
Author       : Wael Hamze
Help         : Tools are installed under {agentroot}/_work/tools. e.g 'D:\Agent1_work\tools\MSCRMBuildTools\9.0.1'`

I've run it again now and I am receiving a different error message regarding XML formatting.

`##[debug]Compress-XrmSolution : Name cannot begin with the '<' character, hexadecimal value 0x3C. Line 289, position 2.`

[PackError.txt](https://github.com/WaelHamze/dyn365-ce-vsts-tasks/files/2902909/PackError.txt)

The Compress-XrmSolution takes the PackParams, I'm not certain where the Compress-XrmSolution is defined unfortunately.

Below is the screenshot of the task setup, yaml config for the task and the map.xml file.

![mscrmpacksolution_screenshot](https://user-images.githubusercontent.com/7306269/53373701-1a095e80-39bb-11e9-9861-cb9157ebfbfb.png)
[map.xml.txt](https://github.com/WaelHamze/dyn365-ce-vsts-tasks/files/2902926/map.xml.txt)
[MSCRMPackSolution_Task_Yaml.txt](https://github.com/WaelHamze/dyn365-ce-vsts-tasks/files/2902923/MSCRMPackSolution_Task_Yaml.txt)

I'll keep testing my side with a few other configs, I tested the XML and did a quick look up and it seems its valid formatting.

**Comment by crmdruid** [comment]
@WaelHamze it's working now, I am not 100% sure as I came back from a meeting and ran it again and it worked.

Thank you for your assistance, it is very much appreciated.

Thank you to the rest of the commentators for their feedback too.

**Comment by WaelHamze** [comment]
Glad this is working now. Thx for flagging this and help with troubleshooting.
