### ISSUE TITLE
MSCRM Package Deployer task XML buffer Exceeded

### ISSUE THREAD

**Issue by markgomez00** [WaelHamze/dyn365-ce-vsts-tasks#51]
When trying to import a package with a base/core solution, we are encountering the error below.

"Importing solution threw exception : The size necessary to buffer the XML content exceeded the buffer quota."

The solution is basically a base solution which contains multiple entities, the size is only 500 kb but contains a lot of entity,forms,view,fields

![image](https://user-images.githubusercontent.com/48013891/53405219-7a27f100-3a0b-11e9-9418-e3d0b2523861.png)

[tasklog_7.log](https://github.com/WaelHamze/dyn365-ce-vsts-tasks/files/2904909/tasklog_7.log)

**Comment by WaelHamze** [comment]
@markgomez00 seems like a problem with the Package Deployer Itself or the file. I suggest you try to replicate this locally and raise a case with MS if needed.

**Comment by WaelHamze** [comment]
Closing as there is no action I can take on this.
