### ISSUE TITLE
CRM Connection Failing with Null Reference Exception

### ISSUE THREAD

**Issue by rswafford** [WaelHamze/dyn365-ce-vsts-tasks#55]
Trying to leverage these scripts against a brand new D365 Online organization, using OAuth, and I am getting null reference exceptions upon logging into CRM. I tracked it down in the code to the line:

crmServiceClient.OrganizationServiceProxy.Timeout = new TimeSpan(0, 0, DefaultTime);

the OrganizationServiceProxy object is null.  I extracted the connection method out to a console app, and gave it the same connection string - the OSP is null, but the OrganizationWebProxyClient is not null.

Connection string looks like this:
Url=https://orgname.crm.dynamics.com; AuthType=OAuth; AppId={guid}; RedirectUri=https://orgname.crm.dynamics.com

the App ID is registered in AzureAD and my user account has authenticated with it successfully. Ideas?

**Comment by WaelHamze** [comment]
@rswafford most user use username/password combination

If you take a look at the examples here: https://docs.microsoft.com/en-us/dynamics365/customer-engagement/developer/xrm-tooling/use-connection-strings-xrm-tooling-connect

This connection string still requires additional credentials

**Comment by WaelHamze** [comment]
Please re-open if you have any further questions
