### ISSUE TITLE
Unable to Login after using AuthType=AD;Url=$(Url) after latest tool release

### ISSUE THREAD

**Issue by Remkovanlaarhoven** [WaelHamze/dyn365-ce-vsts-tasks#57]
I am using Azure Devops to deploy solutions to Dynamics CRM 2016.
Yesterday (12 march) i could use 

> AuthType=AD;Url=$(Url)

 as a connectionstring 

Today i get the following message: 

> Unable to Login to Dynamics CRM

When i use Task 9.* it still works but using 10.* or 11.* i get the unable to login message.

**Comment by Santoshnilla** [comment]
Exactly the same thing is happening from yesterday on. I have to use the task 9.*
Waiting for the fix.

**Comment by spaolortm** [comment]
Same issue here. I'm using this commectionstring :

ServiceUri=;AuthType=IFD;Domain=AMT;User ID=; Password=LoginPrompt=Never; 

Does not wok anymnore since this morming (MSCRMBuild 9.0.10)

**Comment by spaolortm** [comment]
Just found a workaround : Override "D:\Agent1_work\tools\MSCRMBuildTools\9.0.10" with "D:\Agent1_work\tools\MSCRMBuildTools\9.0.9"

Doing that I was able to login again

**Comment by WaelHamze** [comment]
CRM 2016 is not actually supported by this tool. Off course some functionality will work and I am happy to help resolve any issues if possible.

The only change that was done yesterday is using the version 9.0.2.12 of the xrmtooling library instead of previous version.

Is anyone able to create a quick console app to test this using latest and previous version?

What this library does is not under my control but we maybe able to get vendor to fix this issue.

**Comment by Cyb3rzombie** [comment]
> Just found a workaround : Override "D:\Agent1_work\tools\MSCRMBuildTools\9.0.10" with "D:\Agent1_work\tools\MSCRMBuildTools\9.0.9"
> 
> Doing that I was able to login again

Can confirm this is working. For me the issues only happens with onpremise systems. Online is working fine.

Tried it with this small PowerShell script:
`$CrmConnectionString = "AuthType=AD;Username=<username>;Password=<password>;Url=<url>;Domain=<domain>"`

`#New toolkit => Ping not working
#$xrmCIToolkit = "<agent_folder>\_work\tools\MSCRMBuildTools\9.0.10\xRMCIFramework\9.0.0\Xrm.Framework.CI.PowerShell.Cmdlets.dll"`

`#Old toolkit => ping is working
$xrmCIToolkit = "<agent_folder>\_work\tools\MSCRMBuildTools\9.0.9\xRMCIFramework\9.0.0\Xrm.Framework.CI.PowerShell.Cmdlets.dll"`

`Import-Module $xrmCIToolkit
Select-WhoAmI -ConnectionString $CrmConnectionString -Verbose`

**Comment by michsob** [comment]
We have the same problem with on premise systems. It works on version 9.0.9 but fails to connect on 9.0.10.

**Comment by WaelHamze** [comment]
Is everyone who is facing this issue using on-premises and 2016?

Few things to note about the workaround:
1- When I publish a new version in marketplace you will need to do this work around again
2- Eventually one of scripts/cmdlets will change and some tasks will start to break

So comparing .12 with .11
https://www.nuget.org/packages/Microsoft.CrmSdk.XrmTooling.CoreAssembly/

.12 should have actually fix a connectivity issue with on premises. But it seems some things are broken now.

Is someone able to raise a case with MS for this? hopefully they can release .13 hotfix for this

**Comment by spaolortm** [comment]
Hi @WaelHamze,

Maybe you could give us the ability to choose the task version in Azure DevOps ?

![image](https://user-images.githubusercontent.com/45692603/54314062-08c27380-45b1-11e9-8ec8-52ccb72335d9.png)

**Comment by WaelHamze** [comment]
@spaolortm thanks for the suggestion.

That would be a big change actually and lots of regression to support this on all the tasks. In this case the base SDK library is failing which is impacting everything I think. Might be easier to get this fixed or rolled back.

**Comment by michsob** [comment]
Maybe we can consider roll back to previous version of library until issue is resolved?

**Comment by Rishoj** [comment]
We have the same issue on a CRM 9.0 (9.0.2.3034) onprem solution.

**Comment by mpseidel** [comment]
Same here on a CRM 9 on prem `Version 1612 (9.0.2.3034) (DB 9.0.2.3034)`

**Comment by hari44330** [comment]
I am facing the same issue too. Details: CRM OnPrem and is occurring from yesterday
~Hari

**Comment by WaelHamze** [comment]
Looks like due to caching issues some of the code was still using 9.0.2.11 of the xrm tooling: https://www.nuget.org/packages/Microsoft.CrmSdk.XrmTooling.CoreAssembly/

All the code should be using now 9.0.2.12 which should have the fix for the on-premise connectivity issue.

I know it can be very annoying when pipelines start to fail. Hopefully this didn't cause you too much disruption.

I have uploaded the fix to the marketplace. The MSCRM Tools Installer should have a version of 9.0.91. Hopefully this will be propagated to your accounts quickly.

**Comment by michsob** [comment]
Thanks!

I can confirm it works with CRM 2016 on premise.

**Comment by Remkovanlaarhoven** [comment]
I also can confirm it works with CRM 2016 on premise. Thanks for your quick response and good work.

**Comment by WaelHamze** [comment]
Excellent glad the fix worked
