### ISSUE TITLE
Will this tool works with D365 CE on-prem implementation and Azure DevOps

### ISSUE THREAD

**Issue by dsabale** [WaelHamze/dyn365-ce-vsts-tasks#59]
Hi,  

I'm working on my first D365 CE project and one task that we are looking is to implement a CI/CD pipeline. The customer has Azure DevOps account that we used for the project and their D365 CE is on-premise.

I tried to use your tool by adding the Ping and Export Solution tasks in our current build. But for some reason, I was not able to make this works. Here's my questions:
1. Does the tool support the on-premise implementation of D365 CE with Azure DevOps?
2. Can I use any agent or it should be hosted agent?
3. My customer's D365 is configured to use IFD for authentication, do you have any suggestions on the connection string I need to use? They also told me that they have OAuth enabled, will this be better than IFD?
4. For the User Account, what type of access I need to request from my customer to allow me to perform the tasks?

Appreciate any feedback on this.

Thanks

Dindo

**Comment by WaelHamze** [comment]
@dsabale 

1. Yes it does. Most users in this scenario opt to have a private agent install on their local network that has a line of sight to their D365CE instance
2. You need to use your private agent, hosted agent will not be able to see your internal instance. Unless your instance is accessible from the internet
3. You can see supported connection strings here: https://docs.microsoft.com/en-us/dynamics365/customer-engagement/developer/xrm-tooling/use-connection-strings-xrm-tooling-connect
4. You will need "System Administrator" in D365 for solution operations and "Dynamics 365 Service Admin" if you want to use instance management tasks.

Hope this helps.

Wael
