### ISSUE TITLE
MSCRM Pack Solution not including sitemap

### ISSUE THREAD

**Issue by lheng18** [WaelHamze/dyn365-ce-vsts-tasks#62]
I saw a question on it but it was closed and I can reopen it. I put comments in the question thread but not sure if it can be brought into attention. I apologize for submitting it as a new issue here.
<img width="213" alt="Capture" src="https://user-images.githubusercontent.com/48900629/54923049-6cb13a00-4ed7-11e9-9241-0870780c4557.PNG">
 I encountered the same issue. I use Dynamics v9.1 0.2859 and SDK v9 and MSCRM Pack Solution step (v. 10.) and it doesn't pack the contents of the AppModuleSiteMaps directory in the packaged solution zip files. I tried configuring to pack task/step to use the v8.2 SDK but got error. However I am able to pack AppModuleSiteMaps into customization file using SPKL containing latest SDK assembly. I just can't pack it using SCRM Pack Solution step (v. 10.) . Thanks!
Capture

**Comment by lheng18** [comment]
I found this issue Only happens when packing to a managed solution.

**Comment by WaelHamze** [comment]
Re-openend previous issue
