### ISSUE TITLE
Backup tasks succeeded without backup is available

### ISSUE THREAD

**Issue by charliechen179** [WaelHamze/dyn365-ce-vsts-tasks#65]
![image](https://user-images.githubusercontent.com/29467948/55348869-36029300-5486-11e9-9317-bb972924f87d.png)

I have a sample release pipeline that executes backup and then deploys, and deployment should not be started before the backup is done and available or when the backup is still creating.

![image](https://user-images.githubusercontent.com/29467948/55349038-aa3d3680-5486-11e9-81c2-2bfecc617a1d.png)

The backup task can't really know if the backup is done and available,even though it returns the status of the backup request as succeeded. 

![image](https://user-images.githubusercontent.com/29467948/55349274-49fac480-5487-11e9-96e3-1a6814d9a08e.png)

Is there a way to query the backup list and see if the lasted backup is available?  How can I link the opetionId with the id of backup instant? 

Thanks!

**Comment by WaelHamze** [comment]
@charliechen179 thanks for interesting observation, seems like an issue with the API. One would assume that one asyn operation is completed then backup is ready but based on the above it doesn't seem to be the case.

The work around is not very neat. Only thing I can think of is query the backups and try to match it to the provided name and a different timestamp and keep quering that until we get it

Did you discuss your observation with MS?

**Comment by WaelHamze** [comment]
@charliechen179 I have added some additional code to query the list of backups.

Now the backup status is returning as available although the portal is showing as Creating.... which is strange.

However even though it is showing as Creating, I was able to go ahead and start a restore with it.

**Comment by charliechen179** [comment]
Thanks for getting me back. I will test it a little and let you know how it goes.

**Comment by WaelHamze** [comment]
Closing, I added some more code to delay further, Don't think there is anything else I can do to the task at this stage

**Comment by charliechen179** [comment]
Thanks @WaelHamze
