### ISSUE TITLE
Does the tool have copy to new instance from an existing instance feature

### ISSUE THREAD

**Issue by lheng18** [WaelHamze/dyn365-ce-vsts-tasks#67]
I like the tool very much. Thanks for providing it. I saw the Power Shell API available, just wonder if the build task for it is available. 

Thanks!

**Comment by lheng18** [comment]
also create an CDS instance.

**Comment by WaelHamze** [comment]
@lheng18 can you please share the link?

I can't see copy mentioned anywhere here...https://docs.microsoft.com/en-us/powershell/module/microsoft.xrm.onlinemanagementapi/?view=dynamics365ce-ps

**Comment by lheng18** [comment]
You are right. Copying or Cloning CE instance API is not available yet. How about creating a new Power App environment, Enable CDS database and assign user to the environment and delete environment?
Here are the CmdLet list
New-AdminPowerAppEnvironment ,New-AdminPowerAppCdsDatabase ,Set-AdminPowerAppEnvironmentRoleAssignment ,Remove-AdminPowerAppEnvironment 

https://docs.microsoft.com/en-us/power-platform/admin/powerapps-powershell  

Thanks!

**Comment by WaelHamze** [comment]
@lheng18 copy task is there now. If Env is not there, you will need to provision it first using the provision task.
