### ISSUE TITLE
MSCRM Pack Solution error (FLOW)

### ISSUE THREAD

**Issue by drivardxrm** [WaelHamze/dyn365-ce-vsts-tasks#68]
I'm having an issue with the MSCRM Pack Solution task.

I have a solution-aware FLOW in my solution and it makes the solution packager tool crash.
This is a known issue but it is apparently fixed with the latest version of the Core Tools 9.0.3.1
[https://devkeydet.blog/2018/04/10/build-and-deployment-automation-of-a-model-driven-powerapp-using-vsts/](url)

I'm able to pack and unpack locally using the updated Core Tools but my Azure Devops Build is not working using the MSCRM Pack Solution task.
![build error](https://user-images.githubusercontent.com/38399134/56099593-ee93f200-5edc-11e9-85bc-e4f8b8690471.png)

**Comment by WaelHamze** [comment]
@drivardxrm the extension  is using the latest version, what version of the MS Tools Installed is coming up? I presume you have selected 9.0 in the SDK selection?

**Comment by drivardxrm** [comment]
@WaelHamze I'm using Microsoft.CrmSdk.CoreTools V9.0.3.1 (last update April 3)
![2019-04-16_16-10-37](https://user-images.githubusercontent.com/38399134/56241341-9f2bfe00-6063-11e9-8cd2-9f38f75769e7.png)

Using the Solution Packager included in this version, I'm able (locally) to pack and unpack a solution that contains a FLOW. Before I updated to this version, I had the same error that I have using the VSTS BuildTools (see first post).

might be related to issue #69 

Thanks

**Comment by drivardxrm** [comment]
@WaelHamze I was able to make it work. It seems I was not running the latest version of the extension in Azure Devops.  
I didn't find a way to update the extension directly in Azure Devops, I had to uninstall and reinstall. Now my solution with a Flow is packing and unpacking correctly with the tool.

Thanks for your help, these tools are legendary ;)

**Comment by WaelHamze** [comment]
@drivardxrm really glad you got it working. By the way I have released an update yesterday. It will print in the log the version of the Sdk files it is using so users don't have to wonder which version it is using.
