### ISSUE TITLE
Package Deployer Packaging

### ISSUE THREAD

**Issue by berellax** [WaelHamze/dyn365-ce-vsts-tasks#72]
Hi,

I have a build definition in which I am incrementing the version of my solution(s) and then exporting the solution(s), adding to a Package Deployer Package, and publishing the package as an artifact for release. The challenge I’m running into is updating the ImportConfig.xml with the solutions. My current plan is to write a PowerShell script to do this, but wanted to know if you you’ve encountered this issue and have any guidance.

Thanks!
Berel

**Comment by WaelHamze** [comment]
@berellax an easier way to handle this is to keep the name of the solution file fixed (i.e. without version)

But yes you can always add a PowerShell script to adjust the importconfig file as needed during the build
