### ISSUE TITLE
No MSCRM Tool Installer displays

### ISSUE THREAD

**Issue by RogueJin** [WaelHamze/dyn365-ce-vsts-tasks#73]
Hi,

I just installed MSCRM extension to Azure Devops, but I cannot find MSCRM Tool Installer. Does anyone else have the same issue ?
![image](https://user-images.githubusercontent.com/21214103/57204403-342e7100-6fea-11e9-9b7e-7089fef98322.png)

**Comment by harshlive** [comment]
Facing the same issue

**Comment by RogueJin** [comment]
Is there work around to fix the issue?

**Comment by harshlive** [comment]
Tried installing crm tools using ps script in yaml but the extension tasks couldnt look up in that folder.. not sure if there is a way to explicitely define the path in which the tasks should look for the tools

**Comment by WaelHamze** [comment]
@RogueJin @harshlive let me look into this

**Comment by RogueJin** [comment]
@WaelHamze, I have tried to uninstall and re-install the extension, but it still has no installer.
![image](https://user-images.githubusercontent.com/21214103/57576630-e35dc300-7496-11e9-925b-db7d02c6e1a3.png)

**Comment by RogueJin** [comment]
However I downloaded and unzipped the extension file, the tool installer is really there. so weird...

**Comment by WaelHamze** [comment]
@RogueJin that is very weird indeed. Are you using online or TFS?

**Comment by harshlive** [comment]
Using online version, tried reinstalling but I am still having the issue

**Comment by RogueJin** [comment]
@WaelHamze online version

**Comment by RogueJin** [comment]
@WaelHamze What anything can I help for it?

**Comment by WaelHamze** [comment]
@RogueJin did you get this resolved eventually?
