### ISSUE TITLE
Missing documentation.

### ISSUE THREAD

**Issue by sveco** [WaelHamze/dyn365-ce-vsts-tasks#75]
Missing comprehensive documentation: what are options for import and pack json configs. how to create mapping XML file.

**Comment by WaelHamze** [comment]
@sveco you can find examples of the config files in this folder.

https://github.com/WaelHamze/dyn365-ce-devops-sample/tree/master/Sample/Xrm.CI.Framework.Sample/Customizations/Solutions

Mapping file is the standard mapping file used by the solution packager: https://docs.microsoft.com/en-us/dynamics365/customer-engagement/developer/compress-extract-solution-file-solutionpackager#use-the-map-command-argument
