### ISSUE TITLE
Export/ Import question

### ISSUE THREAD

**Issue by bramvdklinkenberg** [WaelHamze/dyn365-ce-vsts-tasks#77]
Hi, I am automating the exporting and importing of solutions via the devops plugin. When using the export task you have to name a specific solution, that would have to make me a build pipeline for every solution we have. is there a way to make that a variable? any ideas about that?

**Comment by bramvdklinkenberg** [comment]
Hi @WaelHamze do you have experience with the above question?

**Comment by WaelHamze** [comment]
@bramvdklinkenberg how many solutions do you have? if they are independent solutions then they could have own build and lifecycle.

Ideally you want your build output to contain everything you need to be able to spin up a new environment and your release should be clever enough to only deploy deltas if needed.

**Comment by bramvdklinkenberg** [comment]
Hi @WaelHamze , I am not a Dynamics expert (haven't worked with it), but I am helping a customer with automating some things and ci/cd in azure devops.
They have tens of solutions, but the plugin is only intended for one solution right? Or can you use something like wildcards (e.g. *)?

**Comment by WaelHamze** [comment]
@bramvdklinkenberg seems like the team will need to rethink how they do solutions, otherwise you will need to make the pipelines complex.

The task will handle one solution, You can take a look at the "MSCRM Import Solution using Config" which handles many solutions.

**Comment by bramvdklinkenberg** [comment]
Hi @WaelHamze , yeah it is something I already mentioned to them. I asked them if it is possible to maybe go back to one solution or maybe sort changes in like 1-5 solutions.

Is there any documentation or examples on what this config file looks like?

**Comment by bramvdklinkenberg** [comment]
Or maybe it's easier to create a solution per sprint. Do you have any experience with multiple solutions?

**Comment by WaelHamze** [comment]
@bramvdklinkenberg I would normally recommend minimum solutions where possible to mimimize layers and maintenance overhead, Yes you would need to add all solutions to config, bare in mind if solution version doesn't change the import will skip.
