### ISSUE TITLE
Import Log Filename Issues

### ISSUE THREAD

**Issue by karan-mittal** [WaelHamze/dyn365-ce-vsts-tasks#78]
Hi,

The MSCRM Import Solution -> Import Log Filename is failing.
We are trying to create the functionality when import solution is failed then it should create a Import log and subsequent Send Email task should send the logs to the Delivery List.

We kept the Logs Directory as empty so that it should take the default path: $env:System_DefaultWorkingDirectory
and in Import Log Filename, we just mentioned - import.xml but we are facing following issue: 
2019-05-23T21:25:43.3449275Z ##[error]The given path's format is not supported.

can you please help? 

Thanks!!

**Comment by karan-mittal** [comment]
@WaelHamze Any help will be highly appreciated.

**Comment by WaelHamze** [comment]
Let me check on this

**Comment by WaelHamze** [comment]
Good spot this is a bug and has been fixed. Will be deployed in next release

**Comment by karan-mittal** [comment]
Thanks Wael. Appreciate it.

**Comment by WaelHamze** [comment]
Released
