### ISSUE TITLE
Getting version of Dynamics 365 solution (Get Version task)

### ISSUE THREAD

**Issue by mpavlino** [WaelHamze/dyn365-ce-vsts-tasks#79]
Hi @WaelHamze ,

It would be nice to get current version of dynamics 365 solution so that we could increment it automatically and possibly automate run of build procedure. 
My suggestion is to create Get Version task or something similar that would get current version of solution either form current crm instance or from xml.

Thank You
Mirko

**Comment by WaelHamze** [comment]
@mpavlino wouldn't you want your build number and the solution version to match? Most users update the solution version based on the build number.

**Comment by evilbaschdi** [comment]
I currently read the Solution Version manually from Solution.xml in the "others" directory.

**Comment by WaelHamze** [comment]
@mpavlino @tomidix There is a "MSCRM Get Solution" task that returns the version amongst other things as an output parameter
