### ISSUE TITLE
Automate online database backup is not working

### ISSUE THREAD

**Issue by Nirmal1510** [WaelHamze/dyn365-ce-vsts-tasks#89]
I am trying to automate solution deployment for Dynamics 365 Customer engagement app using Azure devops.

My build and release are working fine for solution export and import. However, now I also want to add a task for database backup of online instance. I am using task MSCRM Backup online instance. I have filled details as shown in screenshot 1. 

I am using instance name as I see in my admin portal, I tried the entire link of Dynamics 365 Customer engagement app. However, I get an error which says "'instance name'  not found" as shown in the screenshot2.

can you please help me what am I doing wrong?
<img width="523" alt="ScreenShot 1" src="https://user-images.githubusercontent.com/52452094/60508418-c2f9fa00-9cca-11e9-82a0-371d2b8eedeb.PNG">

<img width="455" alt="Screenshot 2" src="https://user-images.githubusercontent.com/52452094/60508442-d2794300-9cca-11e9-8fd4-1b09b198b955.PNG">

**Comment by WaelHamze** [comment]
@Nirmal1510 looks like instance name is not correct or is not visible by the account you are using.

if url is 

https://mycompanydev.crm4.dynamics.com

Instance name should be: mycompanydev
