### ISSUE TITLE
MSCRM_Tools_Path not found

### ISSUE THREAD

**Issue by ychakka** [WaelHamze/dyn365-ce-vsts-tasks#9]
Hello,

I am using your MSCRM Pack solution task to pack all my CRM xml assets into deployable format in my build pipeline. But i encountered following error at your Pack solution task "MSCRM_Tools_path not found. Add MSCRM Tools Installer before this task".

What does it mean? Do i need to install any other extension apart from this? Please help me to resolve this.

Thanks in advance

**Comment by WaelHamze** [comment]
@ychakka you need to add the "MSCRM Tools Installer" Task to your pipeline before other MSCRM tasks. This downloads all the libraries required for all tasks including the Pack. This is included in the same extension.
