### ISSUE TITLE
Error While Restoring CRM Online Instance

### ISSUE THREAD

**Issue by HIREN-AITC** [WaelHamze/dyn365-ce-vsts-tasks#93]
I have taken a backup from my instance1 yesterday. Today I want to restore my instance1 from yesterday's backup.
when I try to restore using Restore CRM Online Instance task it fails with below error.
"Restore-CrmInstance: Parameter set cannot be resolved using the specified named parameters."
I am trying to restore on running instance, do I need to reset it before restoring?

**Comment by WaelHamze** [comment]
@HIREN-AITC you should not need to reset it, are you still facing this issue?

**Comment by HIREN-AITC** [comment]
@WaelHamze  yes I do get the same error, When I contact MS they told Restore functionality in API is not available for CRM 9.0+. They are working on it and soon they will provide new release.

**Comment by WaelHamze** [comment]
@HIREN-AITC this should be fixed by now. Please re-open if you still having issues.
