### ISSUE TITLE
How to get the Patch Instance name that is created using CreatePatch tool

### ISSUE THREAD

**Issue by MustaqueEhiya** [WaelHamze/dyn365-ce-vsts-tasks#95]
Hi team,

I am using the Create Patch option and it created the patch names dynamically like this - Patch solution created with name: **MMA_WWSL_Patch_71d4e0d4**

How to get that name to pass that to the next step ExportSolution to export as Managed Solution?

Thanks
Mustaque

**Comment by WaelHamze** [comment]
This is on my list of things to add in the next release

**Comment by WaelHamze** [comment]
This is now fixed and is returned as output parameter
